// GENERATED by android/telexcore/scripts/gen-wordlists.py from
// TelexCore/Sources/TelexCore/EnglishCollisions.swift + EnglishContextWords.swift.
// DO NOT EDIT — edit the Swift source and regenerate.
package com.viettelex.telexcore

internal object EnglishCollisions {
    val words = WordSet(parseWords(LIST))
    private const val LIST = """
access accessed accessible accessing accessories accessory achievements across actress
address addresses admission admissions advantage advantages affair affairs affect affected
affecting affects affiliate affiliated affiliates affiliation afford affordable aggressive
agricultural agriculture aircraft airport alabama analysis andorra appropriate
architecture arizona arkansas arm arms arrange arranged arrangement arrangements array
arrest arrested arrival arrivals arrive arrived arrives arrow artists arts ask aspects ass
assault assembled assembly assert asserts assess assessed assessing assessment assessments
asset assets assign assigned assignment assignments assist assistance assistant assisted
assists associate associated associates association associations assume assumed assumes
assuming assumption assumptions assurance assure assured atlanta authorized avatar
awareness bahamas barbara barrel barrier barriers barry bars basis bass berry best between
bias bits bizarre blackberry bless blessed boats border born boss boxes brass breasts
brussels buffalo buffer business businesses busy buys canada canberra cardiff career
careers carried carrier carriers carries carroll carry carrying cars cases cassette cast
causes cemetery census character characters charms charter charts chassis cherry
cherrypick chess chief chosen christmas class classes classic classical classics
classified classifieds classroom cliff coast coffee commission commissioner commissions
compressed compression congress consistent constitutes consultants contemporary contractor
contractors controller converter cookbook cordless core corner corporate corporation
correct corrected correction corrections correctly correlation corruption cost costs
courses crisis cross crossing crossword cruises currencies currency current currently
curriculum daddy darkness database databases december decided decisions dedicated deemed
deeper defend delete dense designs dies diff differ difference differences different
differential differently difficult difficulties difficulty diffs dimensions director
directories directors directory discounts discuss discussed discussion discussions disease
diseases disorders displays does donor donors doom door doors dose down dress dressed
dresses dressing dvd dvds earlier earrings effect effective effectively effects efficiency
efficient efficiently effort efforts element elementary elements embassy emission
emissions enterprise enterprises ericsson err error errors essay essays essence essential
essentially essentials essex establish established estimates exists expenses explorer
express expressed expression february ferrari ferry fitness fleece former forward fossil
freeze furniture further fuss gary gene genes genre genres gets ghost gifts glass glasses
glossary goes gore gossip governor grass greece greene griffin gross guess guests guns
guys happiness hardcore hardcover hardware harris harrison harry her here hire hiss honor
honors horrible horror horse hose hospitals host houses hurricane illness implemented
impossible impressed impression impressive incorrect increases incurred independent
institutions interests interior interracial investments irrigation islands issue issued
issues jeff jefferson jeffrey jerry jesse jessica jesus jewellery kansas karma kerry kiss
kissing kits laboratory larger larry last law laws lesbians less lesser lesson lessons
libraries library lies life list listings lists literature loans lose loss losses
madagascar madness major manufacturer maps marks marriage married marriott mary mask mass
massage massive mattress meets melissa mens merry mess message messages messaging
messenger meters metres mirror mirrors miss missed missile missing mission missions
mississippi missouri mistress mixer moderator more morris morrison moss most motors murray
must narrative narrow nasa necessary needed needle nginx nissan northern nose occurred
occurrence occurring off offense offensive offer offered offering offerings offers office
officer officers offices official officially officials offline offset offsetof offshore
omissions operator operators or order ordered ordering orders organization organized
outdoor outdoors outlook pair pairs para paragraph parameter parameters paris parks
particular particularly partner partners partnership parts pass passage passed passenger
passengers passes passing passion passive passport passwd password passwords past pasta
pays peer peers pens per permission permissions perry personals persons pets photos
physics pieces pierre pins piss pissing plaintiff poems poor porn porno ports pose
positions possess possession possibility possible possibly post posts preferences
preferred presents press pressed pressing pressure princess process processed processes
processing processor processors profession professional professor progress progressive
proposals protocol protocols provisions purposes pussy puts quarter questions raw reasons
redeem refer reference references referred refuse regardless releases remember remembered
renaissance represents requests researchers residents resistance response responses
responsible rest results rise risk risks rooms rose russell russia russian sass disk lisk
pisk saw says secretary see seeker seekers seem seemed seems sees selected sense sentences
september server servers session sessions settlement sexo sheffield sheriff sierra sleeve
soon sorry speeches staff staffing stainless starring statistics stderr stress stuff
stuffed submission submissions success successful successfully suffer suffered suffering
sufficient sufficiently suggestions sunglasses superior surgery surrey surround surrounded
surrounding sussex swiss systems tariff task tasks teens temperature temporary tennessee
term terms terrace terraform terrain terrible territories territory terror terrorism
terrorist terrorists terry test tests themes themselves there these thickness thongs those
thousands tier ties tiffany tire tires tissue tomorrow tons toolbox topless town traffic
transactions transferred transmission transsexual trees tries trips troops trust turn
turns universities unless unsubscribe usa uses vary versions verzeichnis vessel vessels
virus visa visits war warranty wars wax websites wireless wisconsin workers writer writers
wrong xanax zero zoom
"""
}

internal object EnglishContextWords {
    val words = WordSet(parseWords(WORDS))
    val restoreOnly = WordSet(parseWords(RESTORE_ONLY))
    val neutralLoanwords = WordSet(parseWords(NEUTRAL))
    const val maxLength = 12
    private const val WORDS = """
i you he she it we they me him her us them my your his its our their mine yours hers ours
theirs this that these those who whom whose which what myself yourself himself herself
itself ourselves themselves is am are was were be been being do does did done doing have
has had having will would shall should can could may might must get gets got go goes going
make makes made take takes took see saw seen know knew want wants need needs like likes
use uses used say says said come comes came think thinks look looks find found give gives
tell work works call calls an the some any every each all both half few many much more
most several enough such other another same of to in on at by for with from into onto up
out off over under about after before between through during without within along across
behind beyond upon and or but nor so yet if then than because while when where why how
though although unless until whether since as not here there now just only also too very
default back down new old good great big small little long high low right left next last
first one two three again always never often still even much day time way man men people
thing things runs loans songs sons moms cams lens rays vans bans tins tans dams hams thus
air ais ams ans arm asn asp bangs barn beer beest bens best bins bits bons boost boots
born burn cans caps cast cats chair chans chaos charm chens chest chips choes choir chose
cons corn cost cums cups cuts dans days deer deest dims dist docs doms dons dust ems ens
eos est gaps gary gays hair hangs hans harm hats hays heer heest here hero hist hits hoest
hongs horn host hungs inf ins ira ist its keeps kens kits langs lans laos last lats lays
leer leest leos lets lips lisa list loes loest longs loops lose lost lots luis mais mans
mary mats mays meest meets mens mere mias most must nams neer neest neos nest nons norm
nuts oer oes oops owns past pest pets pics queens queest quest taxi teest term test thais
thats theer theest there these tims tips tits toer toes toest toms tops towns turn ums ups
uri urw usa usc vary vast vees veest vias visa vons was
"""
    private const val RESTORE_ONLY = """
a wow ok okay oh ah aha hey hi hello yay yeah yep nope oops ouch hmm huh haha hehe lol omg
wtf bye sorry thanks thank please welcome congrats cool wonderful awesome amazing
"""
    private const val NEUTRAL = """
app apps email mail wifi web blog file files link links game games chat team teams fan
fans form font menu tab tabs click share live stream video videos photo photos camera
laptop phone sim online offline admin mod spam virus download upload update comment
comments post posts story feed group groups page pages shop sale size order ship voucher
deal combo view views like likes sub vlog idol hot top vip pro logo banner code demo test
server client account profile password login logout macos ios windows android linux mac
macbook imac iphone ipad ipod airpods apple gmail youtube facebook messenger instagram
tiktok telegram whatsapp viber zalo discord slack zoom chrome safari firefox edge excel
powerpoint outlook onedrive dropbox notion figma canva netflix spotify shopee lazada tiki
grab momo vnpay viettel vinaphone mobifone samsung xiaomi oppo huawei
"""
}

internal fun parseWords(list: String): HashSet<String> {
    val set = HashSet<String>(1024)
    var i = 0
    val n = list.length
    while (i < n) {
        while (i < n && (list[i] == ' ' || list[i] == '\n')) i++
        val s = i
        while (i < n && list[i] != ' ' && list[i] != '\n') i++
        if (i > s) set.add(list.substring(s, i))
    }
    return set
}
