// GENERATED by android/telexcore/scripts/port-swift-tests.py from the Swift XCTests.
// DO NOT EDIT — regenerate. Helpers live in SwiftPortSupport.kt.
package com.viettelex.telexcore

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/** Ported from TelexCore/Tests/TelexCoreTests/AbbreviationDoublerTests.swift. */
class AbbreviationDoublerPortedTest {
    @Test fun testDInitialAbbreviationsStillWork() {
        assertEquals("ĐSQ", commitWith("DDSQ") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ĐHQG", commitWith("DDHQG") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ĐN", commitWith("DDN") { freeMarking = true; liveSpellCheck = true })
        assertEquals("đsq", commitWith("ddsq") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testCancelStillYieldsLiteralDD() {
        assertEquals("DDR", commitWith("DDDR") { freeMarking = true; liveSpellCheck = true })
        assertEquals("dd", commitWith("ddd") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTrailingVowelExitsTheAbbreviationRule() {
        assertEquals("ddsqa", commitWith("ddsqa") { freeMarking = true; liveSpellCheck = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/CollisionPreferenceTests.swift. */
class CollisionPreferencePortedTest {
    @Test fun testVietnameseWinsStandalone() {
        assertEquals("lát", sentenceSplit("last") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("lít", sentenceSplit("list") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("một lít", sentenceSplit("mootj list") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("hí", sentenceSplit("his") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("hí", sentenceSplit("his") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = false })
    }

    @Test fun testEnglishWinsIsTheOldBehavior() {
        assertEquals("last", sentenceSplit("last") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = false })
        assertEquals("list", sentenceSplit("list") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = false })
    }

    @Test fun testEnglishRunStillRestoresUnderVietnamesePriority() {
        assertEquals("the list", sentenceSplit("the list") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("she last", sentenceSplit("she last") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
    }

    @Test fun testInvalidSyllablesAndGesturesUnchanged() {
        assertEquals("text", sentenceSplit("text") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("google", sentenceSplit("google") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("list", sentenceSplit("lisst") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("lít", sentenceSplit("lits") { liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = false })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/ContextEnglishTests.swift. */
class ContextEnglishPortedTest {
    @Test fun testAppDefaultsKeepVietnameseSentenceEndingInDidAsDi() {
        assertEquals("tôi đi", sentenceCtx("tooi did") { freeMarking = true; liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
        assertEquals("tôi đã đi", sentenceCtx("tooi ddax did") { freeMarking = true; liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
    }

    @Test fun testAppDefaultsRestoreDidInEnglishContext() {
        assertEquals("they did", sentenceCtx("they did") { freeMarking = true; liveSpellCheck = true; contextualEnglish = true; collisionPrefersVietnamese = true })
    }

    @Test fun testEnglishRunPrefersEnglish() {
        assertEquals("he is", sentenceCtx("he is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("she is", sentenceCtx("she is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("it is", sentenceCtx("it is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testUppercaseEnglishRun() {
        assertEquals("He is", sentenceCtx("He is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("She is", sentenceCtx("She is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("It is", sentenceCtx("It is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("HE IS", sentenceCtx("HE IS") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("He Is", sentenceCtx("He Is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("Sao í", sentenceCtx("Sao is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("He í", sentenceCtx("He is") { liveSpellCheck = true; contextualEnglish = false })
    }

    @Test fun testVietnameseOrUnknownKeepsVietnamese() {
        assertEquals("sao í", sentenceCtx("sao is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("he sao í", sentenceCtx("he sao is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testOffLeavesTelexUnchanged() {
        assertEquals("he í", sentenceCtx("he is") { liveSpellCheck = true; contextualEnglish = false })
        assertEquals("she í", sentenceCtx("she is") { liveSpellCheck = true; contextualEnglish = false })
        assertEquals("sao í", sentenceCtx("sao is") { liveSpellCheck = true; contextualEnglish = false })
    }

    @Test fun testNoPreviousWordKeepsVietnamese() {
        assertEquals("í", sentenceCtx("is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testHandVettedContextWords() {
        assertEquals("loans", sentenceCtx("loans") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("she loans", sentenceCtx("she loans") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testLoanwordsAreNeutral() {
        assertEquals("email bán hàng", sentenceCtx("email bans hangf") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("app bán", sentenceCtx("app bans") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("the email is", sentenceCtx("the email is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testInterjectionsDoNotSeedEnglish() {
        assertEquals("ok cám ơn", sentenceCtx("ok cams own") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("ok hát", sentenceCtx("ok hats") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("sorry nha", sentenceCtx("sorry nha") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("thanks em", sentenceCtx("thanks em") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("hi cac bạn", sentenceCtx("hi cac banj") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("he bans", sentenceCtx("he bans") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testInterjectionsRestoreInsideAnEnglishRun() {
        assertEquals("wow đẹp quá", sentenceCtx("wow ddepj quas") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testRenderedVietnameseSeedsVietnamese() {
        assertEquals("toi bán í", sentenceCtx("toi bans is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testSpecPhrases() {
        assertEquals("she thus", sentenceCtx("she thus") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("their moms", sentenceCtx("their moms") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("she thú", sentenceCtx("she thus") { liveSpellCheck = true; contextualEnglish = false })
        assertEquals("their móm", sentenceCtx("their moms") { liveSpellCheck = true; contextualEnglish = false })
    }

    @Test fun testUnambiguousVietnameseNeverFlips() {
        assertEquals("he được", sentenceCtx("he dduowcj") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("he tiếng", sentenceCtx("he tieengs") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testPositionSeedsEnglishContext() {
        assertEquals("position is not okay", sentenceCtx("position is not okay") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("github is", sentenceCtx("github is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("Position is", sentenceCtx("Position is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testTonelessVietnameseStillKeepsVietnameseContext() {
        assertEquals("sao í", sentenceCtx("sao is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("khong í", sentenceCtx("khong is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testEscapedEnglishWordSeedsEnglishContext() {
        assertEquals("this is", sentenceCtx("thiss is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("google is", sentenceCtx("gooogle is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("tested is", sentenceCtx("tessted is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("web bán", sentenceCtx("wweb bans") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testDiacriticOnScreenStillEndsTheRun() {
        assertEquals("he thoi í", sentenceCtx("he thoi is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("he thói í", sentenceCtx("he thois is") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testBrandNamesDoNotOpenEnglishRun() {
        assertEquals("macos á em", sentenceCtx("macos as em") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("Macos á em", sentenceCtx("Macos as em") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("zalo á em", sentenceCtx("zalo as em") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("iphone í", sentenceCtx("iphone is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("the macos is", sentenceCtx("the macos is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("position is not okay", sentenceCtx("position is not okay") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testVietnameseAAndConfStayVietnamese() {
        assertEquals("a còn", sentenceCtx("a conf") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("a còn ở đây không", sentenceCtx("a conf owr ddaay khoong") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("he còn", sentenceCtx("he conf") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("it is a test", sentenceCtx("it is a test") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("he is a man", sentenceCtx("he is a man") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testShortAbbreviationsDoNotOpenEnglishRun() {
        assertEquals("he dc is", sentenceCtx("he dc is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("it is", sentenceCtx("it is") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("position is", sentenceCtx("position is") { liveSpellCheck = true; contextualEnglish = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/EdgeCaseTests.swift. */
class EdgeCasePortedTest {
    @Test fun testDoubleHornCancel() {
        assertEquals("ow", composeWith("oww") {})
        assertEquals("uw", composeWith("uww") {})
        assertEquals("aw", composeWith("aww") {})
        assertEquals("huaw", composeWith("huaww") {})
        assertEquals("ưă", composeWith("waw") {})
        assertEquals("ows", composeWith("owws") {})
    }

    @Test fun testTripleAndQuadDCancel() {
        assertEquals("đ", composeWith("dd") {})
        assertEquals("dd", composeWith("ddd") {})
        assertEquals("ddd", composeWith("dddd") {})
    }

    @Test fun testZClearsToneThenRetone() {
        assertEquals("à", composeWith("aszf") {})
        assertEquals("huyên", composeWith("huyeenfz") {})
        assertEquals("azb", composeWith("azb") {})
        assertEquals("bzz", composeWith("bzz") {})
    }

    @Test fun testCancelledEdgeCasesKeepComposed() {
        assertEquals("ow", commitWith("oww") {})
        assertEquals("uw", commitWith("uww") {})
        assertEquals("ddd", commitWith("dddd") {})
        assertEquals("bzz", commitWith("bzz") {})
    }

    @Test fun testEmptyAndSingleChar() {
        assertEquals("", composeWith("") {})
        assertEquals("a", composeWith("a") {})
        assertEquals("b", composeWith("b") {})
        assertEquals("A", composeWith("A") {})
        assertEquals("s", composeWith("s") {})
        assertEquals("f", composeWith("f") {})
        assertEquals("ư", composeWith("w") {})
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/EngineTests.swift. */
class EnginePortedTest {
    @Test fun testUowHornPropagation() {
        assertEquals("trường", composeWith("truowngf") {})
        assertEquals("được", composeWith("dduowcj") {})
        assertEquals("nước", composeWith("nuowcs") {})
        assertEquals("thương", composeWith("thuwowng") {})
        assertEquals("đường", composeWith("dduowngf") {})
        assertEquals("tươi", composeWith("tuowi") {})
        assertEquals("người", composeWith("nguowif") {})
        assertEquals("mười", composeWith("muwowif") {})
        assertEquals("thuở", composeWith("thuowr") {})
        assertEquals("huơ", composeWith("huow") {})
        assertEquals("quở", composeWith("quowr") {})
        assertEquals("quơn", composeWith("quown") {})
        assertEquals("người", composeWith("nguwowif") {})
        assertEquals("được", composeWith("dduowjc") {})
        assertEquals("được", composeWith("dduwojc") {})
        assertEquals("được", composeWith("dduwocj") {})
        assertEquals("trường", composeWith("truwongf") {})
        assertEquals("sương", composeWith("suwong") {})
        assertEquals("người", composeWith("nguwoif") {})
    }

    @Test fun testQuickTelex() {
        assertEquals("ch", composeWith("cc") { freeMarking = true; quickTelex = true })
        assertEquals("gi", composeWith("gg") { freeMarking = true; quickTelex = true })
        assertEquals("kh", composeWith("kk") { freeMarking = true; quickTelex = true })
        assertEquals("ng", composeWith("nn") { freeMarking = true; quickTelex = true })
        assertEquals("qu", composeWith("qq") { freeMarking = true; quickTelex = true })
        assertEquals("ph", composeWith("pp") { freeMarking = true; quickTelex = true })
        assertEquals("th", composeWith("tt") { freeMarking = true; quickTelex = true })
        assertEquals("chào", composeWith("ccaof") { freeMarking = true; quickTelex = true })
        assertEquals("quá", composeWith("qqas") { freeMarking = true; quickTelex = true })
        assertEquals("thư", composeWith("ttuw") { freeMarking = true; quickTelex = true })
        assertEquals("người", composeWith("nnuwowif") { freeMarking = true; quickTelex = true })
        assertEquals("Chào", composeWith("Ccaof") { freeMarking = true; quickTelex = true })
        assertEquals("CHÀO", composeWith("CCAOF") { freeMarking = true; quickTelex = true })
        assertEquals("occ", composeWith("occ") { freeMarking = true; quickTelex = true })
        assertEquals("đ", composeWith("dd") { freeMarking = true; quickTelex = true })
        assertEquals("cc", composeWith("cc") { freeMarking = true })
    }

    @Test fun testStandaloneWCancelLadder() {
        assertEquals("ư", composeWith("w") {})
        assertEquals("w", composeWith("ww") {})
        assertEquals("ww", composeWith("www") {})
        assertEquals("w", composeWith("ww") { freeMarking = true })
        assertEquals("ww", composeWith("www") { freeMarking = true })
        assertEquals("như", composeWith("nhw") {})
        assertEquals("nhw", composeWith("nhww") {})
        assertEquals("ư", composeWith("uw") {})
        assertEquals("uw", composeWith("uww") {})
    }

    @Test fun testFreeMarkingOutOfOrderTyping() {
        assertEquals("đi", composeWith("did") { freeMarking = true })
        assertEquals("thêm", composeWith("theme") { freeMarking = true })
        assertEquals("đi", commitWith("did") { freeMarking = true })
        assertEquals("thêm", commitWith("theme") { freeMarking = true })
        assertEquals("theme", commitWith("themee") { freeMarking = true })
        assertEquals("did", commitWith("didd") { freeMarking = true })
        assertEquals("daua", commitWith("dauaa") { freeMarking = true })
        assertEquals("air", backspaceWith("airrw", 1) { freeMarking = true })
        assertEquals("bes", backspaceWith("bessw", 1) { freeMarking = true })
        assertEquals("bef", backspaceWith("beffw", 1) { freeMarking = true })
        assertEquals("la", backspaceWith("lass", 1) { freeMarking = true })
        assertEquals("thú", commitWith("thus") { freeMarking = true })
        assertEquals("quên", commitWith("queen") { freeMarking = true })
        assertEquals("sóng", commitWith("songs") { freeMarking = true })
        assertEquals("chả", commitWith("char") { freeMarking = true })
        assertEquals("chải", commitWith("chair") { freeMarking = true })
        assertEquals("hải", commitWith("hair") { freeMarking = true })
        assertEquals("lén", commitWith("lens") { freeMarking = true })
        assertEquals("hít", commitWith("hits") { freeMarking = true })
        assertEquals("sét", commitWith("sets") { freeMarking = true })
        assertEquals("bốt", commitWith("boots") { freeMarking = true })
        assertEquals("lót", commitWith("lots") { freeMarking = true })
        assertEquals("thí", commitWith("this") { freeMarking = true })
        assertEquals("hí", commitWith("his") { freeMarking = true })
        assertEquals("í", commitWith("is") { freeMarking = true })
        assertEquals("ò", commitWith("of") { freeMarking = true })
        assertEquals("there", commitWith("there") { freeMarking = true })
        assertEquals("most", commitWith("most") { freeMarking = true })
        assertEquals("must", commitWith("must") { freeMarking = true })
        assertEquals("lưu", composeWith("luuw") { freeMarking = true })
        assertEquals("cứu", composeWith("cuuws") { freeMarking = true })
        assertEquals("đa", composeWith("dad") { freeMarking = true })
        assertEquals("quư", composeWith("quuw") { freeMarking = true })
        assertEquals("luu", composeWith("luu") { freeMarking = true })
        assertEquals("them", composeWith("them") { freeMarking = true })
        assertEquals("did", composeWith("did") {})
        assertEquals("dad", composeWith("dad") {})
        assertEquals("theme", composeWith("theme") {})
    }

    @Test fun testFreeMarkingDoublerCrossesNucleus() {
        assertEquals("dâu", composeWith("daua") { freeMarking = true })
        assertEquals("dấu", composeWith("dauas") { freeMarking = true })
        assertEquals("mấu", composeWith("mauas") { freeMarking = true })
        assertEquals("côt", composeWith("coto") { freeMarking = true })
        assertEquals("âm", composeWith("ama") { freeMarking = true })
        assertEquals("quao", composeWith("quao") { freeMarking = true })
        assertEquals("muâ", composeWith("muaa") { freeMarking = true })
        assertEquals("daua", composeWith("daua") {})
        assertEquals("dauas", composeWith("dauas") { liveSpellCheck = true })
    }

    @Test fun testTeencodeForms() {
        assertEquals("zô", commitWith("zoo") {})
        assertEquals("zị", commitWith("zij") {})
        assertEquals("zậy", commitWith("zaayj") {})
        assertEquals("dzô", commitWith("dzoo") {})
        assertEquals("dzị", commitWith("dzij") {})
        assertEquals("zxkr", commitWith("zxkr") {})
        assertEquals("was", commitWith("was") {})
        assertEquals("wow", commitWith("wow") {})
    }

    @Test fun testUppercaseDAcronymSurvivesAutoRestore() {
        assertEquals("ĐSQ", commitWith("DDSQ") {})
        assertEquals("ĐHQG", commitWith("DDHQG") {})
        assertEquals("ĐN", commitWith("DDN") {})
        assertEquals("DDR", commitWith("DDDR") {})
        assertEquals("đsq", commitWith("ddsq") {})
        assertEquals("ddsqa", commitWith("ddsqa") {})
        assertEquals("Â", commitWith("AA") {})
    }

    @Test fun testDcAbbreviationSurvivesAutoRestore() {
        assertEquals("đc", commitWith("ddc") {})
        assertEquals("đc", composeWith("ddc") {})
        assertEquals("đcs", commitWith("ddcs") {})
    }

    @Test fun testWordInitialWIsFullTelex() {
        assertEquals("ư", composeWith("w") {})
        assertEquals("ưa", composeWith("wa") {})
        assertEquals("ưu", composeWith("wu") {})
        assertEquals("windows", commitWith("windows") {})
        assertEquals("w", composeWith("w") { simpleTelex = true })
        assertEquals("wa", composeWith("wa") { simpleTelex = true })
        assertEquals("w", composeWith("w") { simpleTelex = true; freeMarking = true })
        assertEquals("wa", composeWith("wa") { simpleTelex = true; freeMarking = true })
    }

    @Test fun testFreeMarkingToggle() {
        assertEquals("ama", composeWith("ama") {})
        assertEquals("âm", composeWith("aam") {})
        assertEquals("coto", composeWith("coto") {})
        assertEquals("côt", composeWith("coot") {})
        assertEquals("data", composeWith("data") {})
        assertEquals("trangw", composeWith("trangw") {})
        assertEquals("trăng", composeWith("trawng") {})
        assertEquals("quatw", composeWith("quatw") {})
        assertEquals("âm", composeWith("ama") { freeMarking = true })
        assertEquals("âm", composeWith("aam") { freeMarking = true })
        assertEquals("côt", composeWith("coto") { freeMarking = true })
        assertEquals("trăng", composeWith("trangw") { freeMarking = true })
        assertEquals("trăng", composeWith("trawng") { freeMarking = true })
        assertEquals("quăt", composeWith("quatw") { freeMarking = true })
        assertEquals("người", composeWith("nguoiwf") {})
        assertEquals("nữa", composeWith("nuawx") {})
        assertEquals("trường", composeWith("truowngf") {})
    }

    @Test fun testLiveSpellCheckKeepsValidWords() {
        assertEquals("người", composeWith("nguoiwf") { liveSpellCheck = true })
        assertEquals("trường", composeWith("truwowngf") { liveSpellCheck = true })
        assertEquals("được", composeWith("dduowcj") { liveSpellCheck = true })
    }

    @Test fun testLiveSpellCheckStopsForeignWords() {
        assertEquals("gôgle", composeWith("google") { liveSpellCheck = true })
        assertEquals("gôglex", composeWith("googlex") { liveSpellCheck = true })
        assertEquals("gôglee", composeWith("googlee") { liveSpellCheck = true })
        assertEquals("github", composeWith("github") { liveSpellCheck = true })
        assertNotEquals("gôglex", composeWith("googlex") {})
    }

    @Test fun testModernOrthography() {
        assertEquals("hóa", composeWith("hoas") {})
        assertEquals("hoá", composeWith("hoas") { modernTone = true })
        assertEquals("khỏe", composeWith("khoer") {})
        assertEquals("khoẻ", composeWith("khoer") { modernTone = true })
        assertEquals("thúy", composeWith("thuys") {})
        assertEquals("thuý", composeWith("thuys") { modernTone = true })
        assertEquals("hòe", composeWith("hoef") {})
        assertEquals("hoè", composeWith("hoef") { modernTone = true })
        assertEquals("mùa", composeWith("muaf") { modernTone = true })
        assertEquals("toán", composeWith("toans") { modernTone = true })
    }

    @Test fun testCancelledMarkFollowsValidityRule() {
        assertEquals("is", commitWith("iss") {})
        assertEquals("as", commitWith("ass") {})
        assertEquals("af", commitWith("aff") {})
        assertEquals("a", commitWith("asz") {})
        assertEquals("aa", commitWith("aaa") {})
        assertEquals("mess", composeWith("messs") {})
        assertEquals("ass", composeWith("asss") {})
        assertEquals("bosss", composeWith("bossss") {})
        assertEquals("mess", commitWith("messs") {})
        assertEquals("school", commitWith("school") {})
        assertEquals("toán", commitWith("toans") {})
        assertEquals("hóa", commitWith("hoas") {})
    }

    @Test fun testUpperToneKeyMixedCaseRestores() {
        assertEquals("OmS", composeWith("OmS") {})
        assertEquals("Óm", composeWith("OSm") {})
        assertEquals("Óm", commitWith("OSm") {})
        assertEquals("SaaS", composeWith("SaaS") {})
        assertEquals("JavaScript", composeWith("JavaScript") {})
        assertEquals("SaaS", commitWith("SaaS") {})
        assertEquals("TypeScript", commitWith("TypeScript") {})
        assertEquals("VIỆT", composeWith("VIEEJT") {})
        assertEquals("HÓA", composeWith("HOAS") {})
        assertEquals("hóa", composeWith("hoas") {})
        assertEquals("Việt", composeWith("Vieejt") {})
        assertEquals("Đây", composeWith("DDaay") {})
    }

    @Test fun testWReachesBackOverCoda() {
        assertEquals("mơi", composeWith("moiw") {})
        assertEquals("người", composeWith("nguoiwf") {})
        assertEquals("quă", composeWith("quaw") {})
        assertEquals("thư", composeWith("thw") {})
        assertEquals("ư", composeWith("uw") {})
        assertEquals("quăt", composeWith("quatw") { freeMarking = true })
    }

    @Test fun testUaNucleusHornsU() {
        assertEquals("nữa", composeWith("nuawx") {})
        assertEquals("nữa", composeWith("nuwax") {})
        assertEquals("mưa", composeWith("muaw") {})
        assertEquals("chưa", composeWith("chuaw") {})
        assertEquals("bữa", composeWith("buawx") {})
        assertEquals("tựa", composeWith("tuawj") {})
        assertEquals("hoă", composeWith("hoaw") {})
        assertEquals("hoặc", composeWith("hoawcj") {})
        assertEquals("quăt", composeWith("quawt") {})
        assertEquals("quă", composeWith("quaw") {})
        assertEquals("hưa", composeWith("huaw") {})
        assertEquals("huaw", composeWith("huaww") {})
        assertEquals("huawe", composeWith("huawwe") {})
        assertEquals("huawei", composeWith("huawwei") {})
        assertEquals("huawei", commitWith("huawwei") {})
        assertEquals("huaw", commitWith("huaww") {})
        assertEquals("muaw", composeWith("muaww") {})
        assertEquals("chuaw", composeWith("chuaww") {})
        assertEquals("huaw", composeWith("huaww") { simpleTelex = true })
        assertEquals("huaw", composeWith("huaww") { freeMarking = true })
        assertEquals("huaw", composeWith("huaww") { liveSpellCheck = true })
        assertEquals("hoaw", composeWith("hoaww") {})
        assertEquals("quaw", composeWith("quaww") {})
        assertEquals("lưu", composeWith("luuw") {})
        assertEquals("luuw", composeWith("luuww") {})
        assertEquals("luuw", commitWith("luuww") {})
        assertEquals("luuw", composeWith("luuww") { freeMarking = true })
        assertEquals("ưă", composeWith("waw") {})
        assertEquals("ưaw", composeWith("waww") {})
        assertEquals("thưă", composeWith("thwaw") {})
        assertEquals("ưư", composeWith("wuw") {})
        assertEquals("nuãw", composeWith("nuawxw") {})
    }

    @Test fun testSimpleTelex() {
        assertEquals("cw", composeWith("cw") { simpleTelex = true })
        assertEquals("thw", composeWith("thw") { simpleTelex = true })
        assertEquals("sw", composeWith("sw") { simpleTelex = true })
        assertEquals("ngw", composeWith("ngw") { simpleTelex = true })
        assertEquals("w", composeWith("w") { simpleTelex = true })
        assertEquals("giw", composeWith("giw") { simpleTelex = true })
        assertEquals("ư", composeWith("uw") { simpleTelex = true })
        assertEquals("cư", composeWith("cuw") { simpleTelex = true })
        assertEquals("ă", composeWith("aw") { simpleTelex = true })
        assertEquals("ơ", composeWith("ow") { simpleTelex = true })
        assertEquals("người", composeWith("nguwowif") { simpleTelex = true })
        assertEquals("chưa", composeWith("chuaw") { simpleTelex = true })
        assertEquals("đường", composeWith("dduwowngf") { simpleTelex = true })
        assertEquals("cư", composeWith("cw") {})
        assertEquals("thư", composeWith("thw") {})
    }

    @Test fun testStandaloneWBlocking() {
        assertEquals("kw", composeWith("kw") {})
        assertEquals("qw", composeWith("qw") {})
        assertEquals("ghw", composeWith("ghw") {})
        assertEquals("nghw", composeWith("nghw") {})
        assertEquals("pw", composeWith("pw") {})
        assertEquals("ew", composeWith("ew") {})
        assertEquals("iw", composeWith("iw") {})
        assertEquals("ư", composeWith("w") {})
        assertEquals("was", commitWith("was") {})
        assertEquals("web", commitWith("web") {})
        assertEquals("win", commitWith("win") {})
        assertEquals("write", commitWith("write") {})
        assertEquals("Wow", commitWith("Wow") {})
        assertEquals("would", commitWith("would") {})
        assertEquals("ứa", commitWith("uwas") {})
        assertEquals("cư", composeWith("cw") {})
        assertEquals("sư", composeWith("sw") {})
        assertEquals("thư", composeWith("thw") {})
        assertEquals("chư", composeWith("chw") {})
        assertEquals("ngư", composeWith("ngw") {})
        assertEquals("như", composeWith("nhw") {})
        assertEquals("trư", composeWith("trw") {})
        assertEquals("phư", composeWith("phw") {})
        assertEquals("khư", composeWith("khw") {})
        assertEquals("giư", composeWith("giw") {})
        assertEquals("dư", composeWith("dw") {})
        assertEquals("đư", composeWith("ddw") {})
        assertEquals("ư", composeWith("uw") {})
        assertEquals("ơ", composeWith("ow") {})
        assertEquals("ă", composeWith("aw") {})
    }

    @Test fun testAutoRestoreKeepsRareValidWords() {
        assertFalse("isValidSyllable kw", SyllableValidator.isValidSyllable("kw"))
    }

    @Test fun testAutoRestoreRevertsInvalidWords() {
        assertTrue("isValidSyllable tét", SyllableValidator.isValidSyllable("tét"))
    }

    @Test fun testTrailingDMakesDbar() {
        assertEquals("đan", composeWith("dand") { freeMarking = true })
        assertEquals("đương", composeWith("duwowngd") { freeMarking = true })
        assertEquals("đường", composeWith("duwowngdf") { freeMarking = true })
        assertEquals("dand", composeWith("dand") {})
        assertEquals("đ", composeWith("dd") {})
        assertEquals("dd", composeWith("ddd") {})
        assertEquals("ađ", composeWith("add") {})
    }

    @Test fun testStopCodaToneConstraint() {
        assertEquals("bát", composeWith("bats") {})
        assertEquals("bạt", composeWith("batj") {})
        assertEquals("sách", composeWith("sachs") {})
        assertEquals("học", composeWith("hocj") {})
        assertEquals("cáp", composeWith("caps") {})
        assertEquals("batf", composeWith("batf") {})
        assertEquals("batr", composeWith("batr") {})
        assertEquals("batx", composeWith("batx") {})
        assertEquals("sachf", composeWith("sachf") {})
        assertEquals("capr", composeWith("capr") {})
        assertEquals("hocf", composeWith("hocf") {})
        assertEquals("bat", composeWith("baft") {})
        assertEquals("bat", composeWith("bart") {})
        assertEquals("bat", composeWith("baxt") {})
        assertEquals("bàn", composeWith("banf") {})
        assertEquals("bãng", composeWith("bangx") {})
        assertEquals("bảnh", composeWith("banhr") {})
        assertEquals("làm", composeWith("lamf") {})
    }

    @Test fun testSecretDoesNotSwallowRAfterStopCoda() {
        assertEquals("secr", composeWith("secr") {})
        assertEquals("secret", composeWith("secret") {})
        assertEquals("secret", composeWith("secret") { liveSpellCheck = true })
        assertEquals("secret", commitWith("secret") {})
        assertEquals("secrets", commitWith("secrets") {})
        assertEquals("ừk", composeWith("uwkf") {})
        assertEquals("ưkr", composeWith("uwkr") {})
        assertEquals("ưkx", composeWith("uwkx") {})
    }

    @Test fun testStopCodaToneDropParityAcrossAllCodas() {
        assertEquals("đắk", composeWith("ddawks") {})
        assertEquals("lắk", composeWith("lawks") {})
        assertEquals("đặk", composeWith("ddawkj") {})
        assertEquals("bák", composeWith("baks") {})
        assertEquals("bạk", composeWith("bakj") {})
        assertEquals("khò", composeWith("khof") {})
        assertEquals("bàng", composeWith("bangf") {})
    }

    @Test fun testZClearsToneOrTypesLiteral() {
        assertEquals("z", composeWith("z") {})
        assertEquals("az", composeWith("az") {})
        assertEquals("xyz", composeWith("xyz") {})
        assertEquals("pizza", composeWith("pizza") {})
        assertEquals("a", composeWith("asz") {})
        assertEquals("huyên", composeWith("huyeenfz") {})
    }

    @Test fun testZAsInitialConsonant() {
        assertEquals("zô", composeWith("zoo") {})
        assertEquals("zô", commitWith("zoo") {})
        assertEquals("zây", composeWith("zaay") {})
        assertEquals("zậy", composeWith("zaajy") {})
        assertEquals("zui", composeWith("zui") {})
        assertTrue("isValidSyllable zô", SyllableValidator.isValidSyllable("zô"))
        assertEquals("zip", commitWith("zip") {})
    }

    @Test fun testDzCluster() {
        assertEquals("dzị", composeWith("dzij") {})
        assertEquals("dzị", commitWith("dzij") {})
        assertEquals("dzô", composeWith("dzoo") {})
        assertEquals("dzây", composeWith("dzaay") {})
        assertTrue("isValidSyllable dzị", SyllableValidator.isValidSyllable("dzị"))
    }

    @Test fun testUppercaseAndMixedCase() {
        assertEquals("ĐÂY", composeWith("DDAAY") {})
        assertEquals("Đây", composeWith("Ddaay") {})
        assertEquals("đÂy", composeWith("ddAAy") {})
        assertEquals("HÓA", composeWith("HOAS") {})
        assertEquals("Tiếng", composeWith("Tieengs") {})
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/FreeMarkingRimeTests.swift. */
class FreeMarkingRimePortedTest {
    @Test fun testOeoStaysLiteralRime() {
        assertEquals("ngoèo", composeWith("ngoeof") { freeMarking = true })
        assertEquals("khoèo", composeWith("khoeof") { freeMarking = true })
        assertEquals("ngoằn", composeWith("ngoanwf") { freeMarking = true })
    }

    @Test fun testOaoStaysLiteralRime() {
        assertEquals("ngoáo", composeWith("ngoaos") { freeMarking = true })
    }

    @Test fun testExistingFoldsUntouched() {
        assertEquals("côt", composeWith("coto") { freeMarking = true })
        assertEquals("dâu", composeWith("daua") { freeMarking = true })
        assertEquals("thêm", composeWith("theme") { freeMarking = true })
        assertEquals("côi", composeWith("coio") { freeMarking = true })
        assertEquals("âm", composeWith("ama") { freeMarking = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/GonhanhLearningsTests.swift. */
class GonhanhLearningsPortedTest {
    @Test fun testCommonEnglishRestores() {
        assertEquals("đi", commitWith("did") { freeMarking = true })
        assertEquals("hí", commitWith("his") { freeMarking = true })
        assertEquals("thí", commitWith("this") { freeMarking = true })
    }

    @Test fun testDoubleLetterEnglishFollowsCancelPosition() {
        assertEquals("address", commitWith("address") { freeMarking = true })
        assertEquals("hoas", commitWith("hoass") { freeMarking = true })
    }

    @Test fun testAdjacentDoubleKeepsWhatTheScreenShows() {
        assertEquals("tested", commitWith("tessted") { freeMarking = true })
        assertEquals("Default", commitWith("Deffault") { freeMarking = true })
        assertEquals("hoas", commitWith("hoass") { freeMarking = true })
        assertEquals("banhs", commitWith("banhss") { freeMarking = true })
        assertEquals("is", commitWith("iss") { freeMarking = true })
        assertEquals("af", commitWith("aff") { freeMarking = true })
        assertEquals("google", commitWith("gooogle") { freeMarking = true })
        assertEquals("DDR", commitWith("DDDR") { freeMarking = true })
    }

    @Test fun testVietnameseProtectedWords() {
        assertEquals("sẽ", commitWith("sex") { freeMarking = true })
        assertEquals("tên", commitWith("teen") { freeMarking = true })
        assertEquals("bên", commitWith("been") { freeMarking = true })
        assertEquals("ơn", commitWith("own") { freeMarking = true })
        assertEquals("cả", commitWith("car") { freeMarking = true })
        assertEquals("tô", commitWith("too") { freeMarking = true })
        assertEquals("ít", commitWith("its") { freeMarking = true })
        assertEquals("á", commitWith("as") { freeMarking = true })
        assertEquals("lơ", commitWith("low") { freeMarking = true })
    }

    @Test fun testTeencodeSurvivesInSimpleTelex() {
        assertEquals("wá", commitWith("was") { simpleTelex = true; freeMarking = true })
    }

    @Test fun testDdAbbreviations() {
        assertEquals("đ", commitWith("dd") { freeMarking = true })
        assertEquals("đc", commitWith("ddc") { freeMarking = true })
        assertEquals("đm", commitWith("ddm") { freeMarking = true })
        assertEquals("đkm", commitWith("ddkm") { freeMarking = true })
        assertEquals("Đm", commitWith("Ddm") { freeMarking = true })
        assertEquals("đi", commitWith("ddi") { freeMarking = true })
        assertEquals("điên", commitWith("ddieen") { freeMarking = true })
        assertEquals("dd", commitWith("ddd") { freeMarking = true })
    }

    @Test fun testEthnicNameSyllables() {
        assertEquals("Đắk", commitWith("DDawks") { freeMarking = true })
        assertEquals("Lắk", commitWith("Lawks") { freeMarking = true })
        assertEquals("Krông", commitWith("Kroong") { freeMarking = true })
    }

    @Test fun testCodaKToneRule() {
        assertEquals("DDawk", commitWith("DDawk") { freeMarking = true })
        assertEquals("lawkf", commitWith("lawkf") { freeMarking = true })
        assertEquals("lặk", commitWith("lawkj") { freeMarking = true })
    }

    @Test fun testCollisionRestoreIsCaseInsensitive() {
        assertEquals("Hí", commitWith("His") { freeMarking = true })
        assertEquals("THÍ", commitWith("THIS") { freeMarking = true })
        assertEquals("Of", commitWith("Off") { freeMarking = true })
        assertEquals("OF", commitWith("OFF") { freeMarking = true })
    }

    @Test fun testCancelContractMatrix() {
        assertEquals("Default", commitWith("Deffault") { freeMarking = true })
        assertEquals("default", commitWith("deffault") { freeMarking = true })
        assertEquals("a", commitWith("asz") { freeMarking = true })
        assertEquals("DDR", commitWith("DDDR") { freeMarking = true })
        assertEquals("is", commitWith("iss") { freeMarking = true })
        assertEquals("banhs", commitWith("banhss") { freeMarking = true })
        assertEquals("bos", commitWith("boss") { freeMarking = true })
        assertEquals("mes", commitWith("mess") { freeMarking = true })
        assertEquals("of", commitWith("off") { freeMarking = true })
        assertEquals("off", commitWith("offf") { freeMarking = true })
        assertEquals("google", commitWith("google") { freeMarking = true })
        assertEquals("google", commitWith("gooogle") { freeMarking = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/TeencodeTests.swift. */
class TeencodePortedTest {
    @Test fun testTeencodeOnsetDoesNotStackWithTeencodeRime() {
        assertEquals("wise", commitWith("wise") { freeMarking = true; liveSpellCheck = true; simpleTelex = true })
        assertEquals("wife", commitWith("wife") { freeMarking = true; liveSpellCheck = true; simpleTelex = true })
        assertEquals("wise", commitWith("wise") { freeMarking = true; liveSpellCheck = true })
        assertEquals("wife", commitWith("wife") { freeMarking = true; liveSpellCheck = true })
        assertEquals("wá", commitWith("was") { freeMarking = true; liveSpellCheck = true; simpleTelex = true })
        assertEquals("bíe", commitWith("bies") { freeMarking = true; liveSpellCheck = true })
        assertEquals("mịe", commitWith("miej") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTeencodeDouIsAWordNotARime() {
        assertEquals("đou", commitWith("ddou") { freeMarking = true; liveSpellCheck = true })
        assertEquals("đoi", commitWith("ddoi") { freeMarking = true; liveSpellCheck = true })
        assertEquals("house", commitWith("house") { freeMarking = true; liveSpellCheck = true; simpleTelex = true })
        assertEquals("ddouj", commitWith("ddouj") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTeencodeOyWithOnsetGraveOnly() {
        assertEquals("gòy", commitWith("goyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ròy", commitWith("royf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("zòy", commitWith("zoyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("dzòy", commitWith("dzoyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("chòy", commitWith("choyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("òy", commitWith("oyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("goyj", commitWith("goyj") { freeMarking = true; liveSpellCheck = true })
        assertEquals("goyr", commitWith("goyr") { freeMarking = true; liveSpellCheck = true })
        assertEquals("boyf", commitWith("boyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("toyf", commitWith("toyf") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTeencodeRimeIk() {
        assertEquals("thík", commitWith("thiks") { freeMarking = true; liveSpellCheck = true })
        assertEquals("chík", commitWith("chiks") { freeMarking = true; liveSpellCheck = true })
        assertEquals("thịk", commitWith("thikj") { freeMarking = true; liveSpellCheck = true })
        assertEquals("thicks", commitWith("thicks") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTeencodeHoyJoinsTheGraveWhitelist() {
        assertEquals("hòy", commitWith("hoyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("hoy", commitWith("hoy") { freeMarking = true; liveSpellCheck = true })
        assertEquals("hoys", commitWith("hoys") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTeencodeRimeUk() {
        assertEquals("ừk", commitWith("uwkf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("hừk", commitWith("huwkf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ứk", commitWith("uwks") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ựk", commitWith("uwkj") { freeMarking = true; liveSpellCheck = true })
        assertEquals("uwkr", commitWith("uwkr") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testAllWWordRestoresAtBoundary() {
        assertEquals("www", commitWith("www") { freeMarking = true; liveSpellCheck = true })
        assertEquals("wwww", commitWith("wwww") { freeMarking = true; liveSpellCheck = true })
        assertEquals("www", commitWith("www") { freeMarking = true; liveSpellCheck = true; simpleTelex = true })
        assertEquals("w", commitWith("ww") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testElongationCommits() {
        assertEquals("ạaaaaaaaa", commitWith("ajaaaaaaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("hônggggg", commitWith("hoonggggg") { freeMarking = true; liveSpellCheck = true })
        assertEquals("vânggggg", commitWith("vaanggggg") { freeMarking = true; liveSpellCheck = true })
        assertEquals("cóaaaaaa", commitWith("cosaaaaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("quàaaa", commitWith("quafaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("đẹppppp", commitWith("ddepjpppp") { freeMarking = true; liveSpellCheck = true })
        assertEquals("xinnnn", commitWith("xinnnn") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testIeRimeCommits() {
        assertEquals("bíe", commitWith("bies") { freeMarking = true; liveSpellCheck = true })
        assertEquals("mịe", commitWith("miej") { freeMarking = true; liveSpellCheck = true })
        assertEquals("thíe", commitWith("thies") { freeMarking = true; liveSpellCheck = true })
        assertEquals("mìe", commitWith("mief") { freeMarking = true; liveSpellCheck = true })
        assertEquals("die", commitWith("die") { freeMarking = true; liveSpellCheck = true })
        assertEquals("tie", commitWith("tie") { freeMarking = true; liveSpellCheck = true })
        assertEquals("lie", commitWith("lie") { freeMarking = true; liveSpellCheck = true })
        assertEquals("diet", commitWith("diet") { freeMarking = true; liveSpellCheck = true })
        assertEquals("field", commitWith("field") { freeMarking = true; liveSpellCheck = true })
        assertEquals("client", commitWith("client") { freeMarking = true; liveSpellCheck = true })
        assertEquals("science", commitWith("science") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testElongatedIeSyllable() {
        assertEquals("bíeee", commitWith("bieseee") { freeMarking = true; liveSpellCheck = true })
        assertEquals("bíeeee", commitWith("bieseeee") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testFreezeReEvaluatesOnElongation() {
        assertEquals("có", composeWith("cos") { freeMarking = true; liveSpellCheck = true })
        assertEquals("cóa", composeWith("cosa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("coấ", composeWith("cosaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("cosaa", composeWith("cosaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("cóaaa", composeWith("cosaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("cóaaaa", composeWith("cosaaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("đẹpppp", composeWith("ddepjppp") { freeMarking = true; liveSpellCheck = true })
        assertEquals("đẹppppp", composeWith("ddepjpppp") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ạaaa", composeWith("ajaaaa") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTonePlacementStaysInHead() {
        assertEquals("cóaaaaa", composeWith("cosaaaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ạaaaaa", composeWith("ajaaaaaa") { freeMarking = true; liveSpellCheck = true })
        assertEquals("quàaaa", composeWith("quafaaaa") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testEnglishGuards() {
        assertEquals("retore", commitWith("retore") { freeMarking = true; liveSpellCheck = true })
        assertEquals("google", commitWith("google") { freeMarking = true; liveSpellCheck = true })
        assertEquals("hí", commitWith("his") { freeMarking = true; liveSpellCheck = true })
        assertEquals("excess", commitWith("excess") { freeMarking = true; liveSpellCheck = true })
        assertEquals("vibes", commitWith("vibes") { freeMarking = true; liveSpellCheck = true })
        assertEquals("pas", commitWith("pass") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testIeRimeEnglishWordsAreDictProtected() {
        assertEquals("bíe", commitWith("bies") { freeMarking = true; liveSpellCheck = true })
        assertEquals("mịe", commitWith("miej") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testVniTeencode() {
        assertEquals("bíe", commitWith("bie1") { vniMode = true; freeMarking = true; liveSpellCheck = true })
        assertEquals("mịe", commitWith("mie5") { vniMode = true; freeMarking = true; liveSpellCheck = true })
        assertEquals("cóaaaaaaa", commitWith("co1aaaaaaa") { vniMode = true; freeMarking = true; liveSpellCheck = true })
        assertEquals("hônggggg", commitWith("ho6nggggg") { vniMode = true; freeMarking = true; liveSpellCheck = true })
        assertEquals("vânggggg", commitWith("va6nggggg") { vniMode = true; freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testStandaloneOyTakesTonesLikeOi() {
        assertEquals("òy", commitWith("oyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("óy", commitWith("oys") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ọy", commitWith("oyj") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ỏy", commitWith("oyr") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testUppercaseVariant() {
        assertEquals("Òy", commitWith("Oyf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("Ừm", commitWith("Uwmf") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testEnglishOnsetWordsAreUntouched() {
        assertEquals("boys", commitWith("boys") { freeMarking = true; liveSpellCheck = true })
        assertEquals("toys", commitWith("toys") { freeMarking = true; liveSpellCheck = true })
        assertEquals("joys", commitWith("joys") { freeMarking = true; liveSpellCheck = true })
        assertEquals("oyster", commitWith("oyster") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testValidatorScopeZeroOnsetPlusGraveWhitelist() {
        assertTrue("isValidSyllable òy", SyllableValidator.isValidSyllable("òy"))
        assertTrue("isValidSyllable oy", SyllableValidator.isValidSyllable("oy"))
        assertTrue("isValidSyllable gòy", SyllableValidator.isValidSyllable("gòy"))
        assertTrue("isValidSyllable chòy", SyllableValidator.isValidSyllable("chòy"))
        assertFalse("isValidSyllable góy", SyllableValidator.isValidSyllable("góy"))
        assertFalse("isValidSyllable bòy", SyllableValidator.isValidSyllable("bòy"))
        assertTrue("isValidPrefix oy", SyllableValidator.isValidPrefix("oy"))
        assertFalse("isValidPrefix oyt", SyllableValidator.isValidPrefix("oyt"))
    }

    @Test fun testStandaloneUmUnCompose() {
        assertEquals("ưm", commitWith("uwm") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ưn", commitWith("uwn") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testTonesOnUm() {
        assertEquals("ừm", commitWith("uwmf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ứm", commitWith("uwms") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ựm", commitWith("uwmj") { freeMarking = true; liveSpellCheck = true })
        assertEquals("ừn", commitWith("uwnf") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testOnsetsRideAlong() {
        assertEquals("hừm", commitWith("huwmf") { freeMarking = true; liveSpellCheck = true })
        assertEquals("hửm", commitWith("huwmr") { freeMarking = true; liveSpellCheck = true })
    }

    @Test fun testValidatorAcceptsNewRimes() {
        assertTrue("isValidSyllable ưm", SyllableValidator.isValidSyllable("ưm"))
        assertTrue("isValidSyllable ừm", SyllableValidator.isValidSyllable("ừm"))
        assertTrue("isValidSyllable ưn", SyllableValidator.isValidSyllable("ưn"))
        assertFalse("isValidSyllable ưnh", SyllableValidator.isValidSyllable("ưnh"))
    }

    @Test fun testEnglishStaysUntouched() {
        assertEquals("unwind", commitWith("unwind") { freeMarking = true; liveSpellCheck = true })
        assertEquals("umbrella", commitWith("umbrella") { freeMarking = true; liveSpellCheck = true })
        assertEquals("column", commitWith("column") { freeMarking = true; liveSpellCheck = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/TeencodeToggleTests.swift. */
class TeencodeTogglePortedTest {
    @Test fun testEnglishWordsFromTheIssueSurviveWhenOff() {
        assertEquals("worry", sentenceToggle("worry") { liveSpellCheck = true; simpleTelex = true; teencode = false })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/ToneClearRetoneTests.swift. */
class ToneClearRetonePortedTest {
    @Test fun testZClearsThenToneReapplies() {
        assertEquals("tối", composeWith("tooiszs") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("tối", commitWith("tooiszs") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("tồi", composeWith("tooiszf") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("tôi", composeWith("tooisz") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("việt", composeWith("vieejtzj") { liveSpellCheck = true; contextualEnglish = true })
    }

    @Test fun testVNIZeroClearsThenToneReapplies() {
        assertEquals("tôi", composeWith("toi610") { vniMode = true })
        assertEquals("tối", composeWith("toi6101") { vniMode = true })
    }

    @Test fun testEnglishDoubleTapGestureUnchanged() {
        assertEquals("pizza", composeWith("pizza") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("jazz", composeWith("jazz") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("tested", commitWith("tessted") { liveSpellCheck = true; contextualEnglish = true })
        assertEquals("hosts", commitWith("hosts") { liveSpellCheck = true; contextualEnglish = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/TypingMatrixTests.swift. */
class TypingMatrixPortedTest {
    @Test fun testTonePositionRelativeToCoda() {
        assertEquals("cáp", composeWith("casp") { englishWordRestore = false })
        assertEquals("cáp", composeWith("caps") { englishWordRestore = false })
        assertEquals("bạt", composeWith("batj") { englishWordRestore = false })
        assertEquals("bạt", composeWith("bajt") { englishWordRestore = false })
        assertEquals("toán", composeWith("toasn") { englishWordRestore = false })
        assertEquals("toán", composeWith("toans") { englishWordRestore = false })
        assertEquals("hoàng", composeWith("hoafng") { englishWordRestore = false })
        assertEquals("hoàng", composeWith("hoangf") { englishWordRestore = false })
    }

    @Test fun testUowConvergence() {
        assertEquals("nước", composeWith("nuwowcs") { englishWordRestore = false })
        assertEquals("người", composeWith("nguwowif") { englishWordRestore = false })
    }

    @Test fun testTrailingDConversion() {
        assertEquals("dand", composeWith("dand") { englishWordRestore = false })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/VNIHornUURetargetTests.swift. */
class VNIHornUURetargetPortedTest {
    @Test fun testHornOnDoubleUTargetsFirstU() {
        assertEquals("ưu", composeWith("uu7") { vniMode = true })
        assertEquals("lưu", composeWith("luu7") { vniMode = true })
        assertEquals("cứu", composeWith("cuu71") { vniMode = true })
        assertEquals("ưu", composeWith("u7u") { vniMode = true })
    }

    @Test fun testSingleUAndUaUnchanged() {
        assertEquals("mưa", composeWith("mua7") { vniMode = true })
        assertEquals("tư", composeWith("tu7") { vniMode = true })
    }

    @Test fun testQuGlideExcluded() {
        assertEquals("quư", composeWith("quu7") { vniMode = true })
        assertEquals("quu7", composeWith("quu77") { vniMode = true })
    }

    @Test fun testSecondHornCancelsFirstU() {
        assertEquals("luu7", composeWith("luu77") { vniMode = true })
        assertEquals("uu7", composeWith("uu77") { vniMode = true })
        assertEquals("cuu75", composeWith("cuu775") { vniMode = true })
        assertEquals("tu7", composeWith("tu77") { vniMode = true })
        assertEquals("hua7", composeWith("hua77") { vniMode = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/VNITests.swift. */
class VNIPortedTest {
    @Test fun testSingleVowelTonesAndMarks() {
        assertEquals("á", composeWith("a1") { vniMode = true })
        assertEquals("à", composeWith("a2") { vniMode = true })
        assertEquals("ả", composeWith("a3") { vniMode = true })
        assertEquals("ã", composeWith("a4") { vniMode = true })
        assertEquals("ạ", composeWith("a5") { vniMode = true })
        assertEquals("â", composeWith("a6") { vniMode = true })
        assertEquals("ă", composeWith("a8") { vniMode = true })
        assertEquals("ê", composeWith("e6") { vniMode = true })
        assertEquals("ô", composeWith("o6") { vniMode = true })
        assertEquals("ơ", composeWith("o7") { vniMode = true })
        assertEquals("ư", composeWith("u7") { vniMode = true })
        assertEquals("đ", composeWith("d9") { vniMode = true })
        assertEquals("ấ", composeWith("a61") { vniMode = true })
        assertEquals("ậ", composeWith("a65") { vniMode = true })
        assertEquals("ắ", composeWith("a81") { vniMode = true })
        assertEquals("ớ", composeWith("o71") { vniMode = true })
        assertEquals("ự", composeWith("u75") { vniMode = true })
        assertEquals("ế", composeWith("e61") { vniMode = true })
        assertEquals("Á", composeWith("A1") { vniMode = true })
        assertEquals("Đ", composeWith("D9") { vniMode = true })
    }

    @Test fun testAuthoritativeReferenceExamples() {
        assertEquals("trường", composeWith("truong72") { vniMode = true })
        assertEquals("Việt", composeWith("Vie65t") { vniMode = true })
        assertEquals("được", composeWith("d9uo7c5") { vniMode = true })
        assertEquals("người", composeWith("nguoi72") { vniMode = true })
        assertEquals("tiếng", composeWith("tie61ng") { vniMode = true })
        assertEquals("học", composeWith("hoc5") { vniMode = true })
        assertEquals("toàn", composeWith("toa2n") { vniMode = true })
        assertEquals("thường", composeWith("thu7o7ng2") { vniMode = true })
        assertEquals("đại", composeWith("d9a5i") { vniMode = true })
        assertEquals("hơn", composeWith("ho7n") { vniMode = true })
        assertEquals("bằng", composeWith("ba8ng2") { vniMode = true })
    }

    @Test fun testMarkToneOrderIndependence() {
        assertEquals("ấ", composeWith("a61") { vniMode = true })
    }

    @Test fun testCancelAndClear() {
        assertEquals("a1", composeWith("a11") { vniMode = true })
        assertEquals("a", composeWith("a10") { vniMode = true })
        assertEquals("a", commitWith("a10") { vniMode = true; liveSpellCheck = false })
        assertEquals("a6", composeWith("a66") { vniMode = true })
        assertEquals("a8", composeWith("a88") { vniMode = true })
        assertEquals("u7", composeWith("u77") { vniMode = true })
        assertEquals("o7", composeWith("o77") { vniMode = true })
        assertEquals("d9", composeWith("d99") { vniMode = true })
        assertEquals("a0", composeWith("a0") { vniMode = true })
    }

    @Test fun testLiteralNumbers() {
        assertEquals("mp3", commitWith("mp3") { vniMode = true; liveSpellCheck = false })
        assertEquals("2020", commitWith("2020") { vniMode = true; liveSpellCheck = false })
        assertEquals("3g", commitWith("3g") { vniMode = true; liveSpellCheck = false })
        assertEquals("html5", commitWith("html5") { vniMode = true; liveSpellCheck = true })
        assertEquals("abc123", commitWith("abc123") { vniMode = true; liveSpellCheck = true })
        assertEquals("Windows10", commitWith("Windows10") { vniMode = true; liveSpellCheck = true })
        assertEquals("hello", commitWith("hello") { vniMode = true; liveSpellCheck = false })
    }

    @Test fun testStopCodaRejectsToneDigitAsLiteral() {
        assertEquals("sec3", composeWith("sec3") { vniMode = true })
        assertEquals("bat2", composeWith("bat2") { vniMode = true })
        assertEquals("bat3", composeWith("bat3") { vniMode = true })
        assertEquals("bat4", composeWith("bat4") { vniMode = true })
        assertEquals("bát", composeWith("bat1") { vniMode = true })
        assertEquals("bạt", composeWith("bat5") { vniMode = true })
    }

    @Test fun testInvalidTokenRestoresRaw() {
        assertEquals("xyz1", commitWith("xyz1") { vniMode = true; liveSpellCheck = false })
    }

    @Test fun testBackspace() {
        assertEquals("tiến", backspaceWith("tie61ng", 1) { vniMode = true })
    }
}

/** Ported from TelexCore/Tests/TelexCoreTests/ValidatorTests.swift. */
class ValidatorPortedTest {
    @Test fun testQuGlideKeepsTheUInTheRime() {
        assertTrue("isValidSyllable quyn", SyllableValidator.isValidSyllable("quyn"))
    }

    @Test fun testToneCodaConstraint() {
        assertTrue("isValidSyllable các", SyllableValidator.isValidSyllable("các"))
        assertTrue("isValidSyllable cạc", SyllableValidator.isValidSyllable("cạc"))
        assertFalse("isValidSyllable càc", SyllableValidator.isValidSyllable("càc"))
        assertFalse("isValidSyllable cảc", SyllableValidator.isValidSyllable("cảc"))
        assertFalse("isValidSyllable cãc", SyllableValidator.isValidSyllable("cãc"))
        assertFalse("isValidSyllable cac", SyllableValidator.isValidSyllable("cac"))
        assertTrue("isValidSyllable càn", SyllableValidator.isValidSyllable("càn"))
        assertTrue("isValidSyllable cạnh", SyllableValidator.isValidSyllable("cạnh"))
        assertTrue("isValidSyllable cảng", SyllableValidator.isValidSyllable("cảng"))
    }

    @Test fun testOnsetRules() {
        assertTrue("isValidSyllable nghe", SyllableValidator.isValidSyllable("nghe"))
        assertTrue("isValidSyllable nghĩ", SyllableValidator.isValidSyllable("nghĩ"))
        assertTrue("isValidSyllable quà", SyllableValidator.isValidSyllable("quà"))
        assertTrue("isValidSyllable gì", SyllableValidator.isValidSyllable("gì"))
        assertTrue("isValidSyllable gia", SyllableValidator.isValidSyllable("gia"))
        assertFalse("isValidSyllable fga", SyllableValidator.isValidSyllable("fga"))
        assertFalse("isValidSyllable ", SyllableValidator.isValidSyllable(""))
    }

    @Test fun testValidPrefixAcceptsRealWords() {
        assertTrue("isValidPrefix ", SyllableValidator.isValidPrefix(""))
    }

    @Test fun testValidSyllableStringFacadeEdges() {
        assertFalse("isValidSyllable ", SyllableValidator.isValidSyllable(""))
        assertTrue("isValidSyllable VIỆT", SyllableValidator.isValidSyllable("VIỆT"))
        assertTrue("isValidSyllable Người", SyllableValidator.isValidSyllable("Người"))
        assertFalse("isValidSyllable a1", SyllableValidator.isValidSyllable("a1"))
        assertFalse("isValidSyllable hó-a", SyllableValidator.isValidSyllable("hó-a"))
        assertFalse("isValidSyllable óá", SyllableValidator.isValidSyllable("óá"))
    }

    @Test fun testValidPrefixStringFacadeEdges() {
        assertTrue("isValidPrefix ", SyllableValidator.isValidPrefix(""))
        assertTrue("isValidPrefix NGƯ", SyllableValidator.isValidPrefix("NGƯ"))
        assertFalse("isValidPrefix a1", SyllableValidator.isValidPrefix("a1"))
    }
}
