// EnglishCollisions.swift — SINH TỰ ĐỘNG bởi gen-english, ĐỪNG SỬA TAY.
// Từ tiếng Anh phổ biến (top-4000) mà Telex mặc định biến thành âm tiết
// Việt hợp lệ (validator không cứu được) — force-restore ở word boundary.
// Đã loại các từ mà tiếng Việt thắng (sẽ=sex, ơn=own… — xem gen-english).
// Regenerate:  swift run gen-english google-10000-english.txt 4000 //              Sources/TelexCore/EnglishCollisions.swift
enum EnglishCollisions {
    /// Sorted ascii, lowercase. ~467 từ, tra Set ở boundary (không trên hot path).
    static let words: Set<String> = [        "access", "accessible", "accessories", "accessory", "across", "address", "addresses", "affairs",
        "affect", "affected", "affiliate", "affiliates", "affordable", "agricultural", "agriculture", "aircraft",
        "airport", "analysis", "appropriate", "architecture", "arizona", "arkansas", "arm", "arms",
        "arrangements", "array", "artists", "arts", "ask", "aspects", "ass", "assembly",
        "assessment", "asset", "assets", "assigned", "assist", "assistance", "assistant", "associate",
        "associated", "associates", "association", "assume", "authorized", "awareness", "barbara", "bars",
        "basis", "bass", "best", "bits", "bless", "boots", "border", "born",
        "boss", "boxes", "brass", "breasts", "buffalo", "business", "businesses", "career",
        "careers", "carried", "carrier", "carry", "cars", "cases", "cast", "causes",
        "census", "chair", "char", "character", "characters", "charter", "charts", "chess",
        "chosen", "christmas", "class", "classes", "classic", "classical", "classified", "classifieds",
        "classroom", "cliff", "coast", "coffee", "commission", "congress", "consistent", "constitutes",
        "consultants", "contemporary", "contractor", "contractors", "controller", "converter", "core", "corner",
        "corporate", "corporation", "correct", "cost", "costs", "courses", "crisis", "cross",
        "cruises", "currency", "current", "currently", "curriculum", "databases", "days", "decisions",
        "designs", "diff", "difference", "differences", "different", "difficult", "dimensions", "director",
        "directories", "directors", "directory", "discounts", "discuss", "discussed", "discussion", "discussions",
        "disease", "diseases", "disorders", "displays", "does", "door", "doors", "down",
        "dress", "dvd", "dvds", "earlier", "effect", "effective", "effectively", "effects",
        "efficiency", "efficient", "effort", "efforts", "enterprise", "enterprises", "ericsson", "error",
        "errors", "essential", "establish", "established", "estimates", "exists", "expenses", "explorer",
        "express", "expressed", "expression", "february", "fitness", "former", "forward", "furniture",
        "further", "fuss", "gary", "gas", "gene", "genre", "gets", "gifts",
        "glass", "glossary", "goes", "governor", "grass", "gross", "guess", "guests",
        "guys", "hair", "hardcore", "hardcover", "hardware", "harry", "has", "her",
        "here", "his", "hiss", "hits", "horse", "hospitals", "host", "houses",
        "if", "increases", "institutions", "interests", "interior", "interracial", "investments", "is",
        "islands", "issue", "issued", "issues", "jeff", "jesus", "kansas", "kiss",
        "kits", "laboratory", "larger", "last", "law", "laws", "lens", "les",
        "lesbians", "less", "lesson", "lessons", "libraries", "library", "list", "listings",
        "lists", "literature", "loans", "lose", "loss", "lost", "lots", "major",
        "manufacturer", "maps", "marks", "marriage", "married", "mary", "mass", "massage",
        "massive", "meets", "mens", "mess", "message", "messages", "messenger", "mirror",
        "miss", "missed", "missing", "mission", "mississippi", "missouri", "mix", "moderator",
        "more", "moss", "most", "must", "narrow", "nasa", "necessary", "nor",
        "northern", "occurred", "of", "off", "offer", "offered", "offering", "offers",
        "office", "officer", "officers", "offices", "official", "officials", "offline", "operator",
        "operators", "or", "order", "ordered", "ordering", "orders", "organization", "organized",
        "pair", "para", "paragraph", "parameter", "parameters", "paris", "parks", "particular",
        "particularly", "partner", "partners", "partnership", "parts", "pass", "passed", "password",
        "past", "peer", "per", "permission", "personals", "persons", "pets", "photos",
        "physics", "pieces", "poor", "porn", "porno", "ports", "positions", "possible",
        "possibly", "post", "posts", "preferences", "preferred", "presents", "press", "pressure",
        "process", "processes", "processing", "processor", "professional", "professor", "progress", "proposals",
        "provisions", "purposes", "pussy", "quarter", "queen", "questions", "raw", "reasons",
        "refer", "reference", "references", "referred", "releases", "represents", "requests", "researchers",
        "residents", "resistance", "response", "responses", "responsible", "rest", "results", "risks",
        "rooms", "rose", "runs", "russia", "russian", "saw", "says", "secretary",
        "see", "seem", "seems", "sense", "server", "servers", "session", "sessions",
        "sets", "sexo", "songs", "soon", "sorry", "staff", "stainless", "statistics",
        "stress", "stuff", "submission", "success", "successful", "successfully", "sufficient", "suggestions",
        "superior", "surgery", "swiss", "systems", "task", "tasks", "teens", "temperature",
        "temporary", "tennessee", "term", "terms", "territory", "test", "tests", "themes",
        "themselves", "there", "these", "this", "those", "thousands", "thus", "tips",
        "tits", "tomorrow", "town", "traffic", "transactions", "transmission", "tree", "trees",
        "trust", "turn", "universities", "unless", "unsubscribe", "us", "usa", "uses",
        "vary", "versions", "verzeichnis", "virus", "visa", "visits", "war", "warranty",
        "wars", "websites", "wireless", "wisconsin", "won", "workers", "writer", "writers",
        "wrong", "zero", "zoom",
    ]
}