#!/usr/bin/env python3
"""Regenerate EnglishWordLists.kt from the Swift sources (single source of truth).
Run from anywhere:  python3 android/telexcore/scripts/gen-wordlists.py
"""
import os, re
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.abspath(os.path.join(here, "..", "..", ".."))
src = os.path.join(root, "TelexCore", "Sources", "TelexCore")
out = os.path.join(here, "..", "src", "main", "kotlin", "com", "viettelex", "telexcore", "EnglishWordLists.kt")

def blocks(text):
    return re.findall(r'"""\n(.*?)"""', text, re.S)

def words(block):
    return [w for w in re.split(r"[ \n]+", block) if w]

def section(text, start, end):
    i = text.index(start)
    j = text.index(end, i + len(start)) if end else len(text)
    return text[i:j]

coll = open(os.path.join(src, "EnglishCollisions.swift")).read()
ctx = open(os.path.join(src, "EnglishContextWords.swift")).read()

collisions = [w for b in blocks(section(coll, "private static let list", None)) for w in words(b)]
neutral = [w for b in blocks(section(ctx, "static let neutralLoanwords", "static let maxLength")) for w in words(b)]
ctxwords = [w for b in blocks(section(ctx, "private static let wordList", "private static let restoreOnlyList")) for w in words(b)]
restore = [w for b in blocks(section(ctx, "private static let restoreOnlyList", None)) for w in words(b)]
maxlen = re.search(r"static let maxLength = (\d+)", ctx).group(1)

def lit(ws):
    lines, cur = [], ""
    for w in ws:
        if len(cur) + len(w) + 1 > 90:
            lines.append(cur); cur = ""
        cur = (cur + " " + w) if cur else w
    if cur: lines.append(cur)
    return "\n".join(lines)

with open(out, "w") as f:
    f.write("// GENERATED by android/telexcore/scripts/gen-wordlists.py from\n")
    f.write("// TelexCore/Sources/TelexCore/EnglishCollisions.swift + EnglishContextWords.swift.\n")
    f.write("// DO NOT EDIT — edit the Swift source and regenerate.\n")
    f.write("package com.viettelex.telexcore\n\n")
    f.write("internal object EnglishCollisions {\n")
    f.write("    val words = WordSet(parseWords(LIST))\n")
    f.write('    private const val LIST = """\n' + lit(collisions) + '\n"""\n}\n\n')
    f.write("internal object EnglishContextWords {\n")
    f.write("    val words = WordSet(parseWords(WORDS))\n")
    f.write("    val restoreOnly = WordSet(parseWords(RESTORE_ONLY))\n")
    f.write("    val neutralLoanwords = WordSet(parseWords(NEUTRAL))\n")
    f.write(f"    const val maxLength = {maxlen}\n")
    f.write('    private const val WORDS = """\n' + lit(ctxwords) + '\n"""\n')
    f.write('    private const val RESTORE_ONLY = """\n' + lit(restore) + '\n"""\n')
    f.write('    private const val NEUTRAL = """\n' + lit(neutral) + '\n"""\n}\n\n')
    f.write("internal fun parseWords(list: String): HashSet<String> {\n")
    f.write("    val set = HashSet<String>(1024)\n")
    f.write("    var i = 0\n    val n = list.length\n")
    f.write("    while (i < n) {\n")
    f.write("        while (i < n && (list[i] == ' ' || list[i] == '\\n')) i++\n")
    f.write("        val s = i\n")
    f.write("        while (i < n && list[i] != ' ' && list[i] != '\\n') i++\n")
    f.write("        if (i > s) set.add(list.substring(s, i))\n")
    f.write("    }\n    return set\n}\n")
print(len(collisions), len(ctxwords), len(restore), len(neutral))
