// SeedData.swift — GENERATED: seed ban đầu cho UserLangModel (lần đầu chạy /
// sau khi user bấm "Xóa từ đã học"). Nguồn: corpus OpenSubtitles2018 tiếng Việt
// (văn nói) lọc bias phim ảnh + bù lớp chat/teencode curated + ~112 từ tiếng
// Anh cơ bản hay pha trong chat Việt. Weight log-scale, max 50 — user gõ thật
// (+1/lần, accepted +2) sẽ vượt seed sau vài ngày; decay tuần làm seed mờ dần.
import Foundation

// PERF: computed var (không phải stored let) — literal ~1400 entries chỉ build
// khi thật sự seed (store trống), giải phóng ngay sau đó thay vì găm
// ~150-250KB suốt đời keyboard; seedIfEmpty nhận @autoclosure nên store đã có
// dữ liệu thì literal không bao giờ được build.
enum SeedData {
    static var unigrams: [String: Int] { [
        "không": 47, "tôi": 48, "anh": 49, "là": 47, "có": 44, "của": 42, "đi": 42, "đã": 42,
        "gì": 41, "sẽ": 41, "ta": 41, "và": 41, "đó": 41, "được": 41, "cô": 40, "một": 40,
        "này": 40, "phải": 40, "rồi": 40, "cho": 39, "người": 39, "em": 50, "làm": 38, "nó": 38,
        "đây": 38, "ở": 38, "biết": 37, "con": 37, "cậu": 37, "với": 37, "ông": 37, "lại": 36,
        "nói": 36, "cái": 35, "ra": 35, "sao": 35, "đang": 35, "để": 35, "ấy": 35, "muốn": 34,
        "mà": 34, "nhưng": 34, "những": 34, "trong": 34, "đến": 34, "khi": 33, "nào": 33, "vậy": 33,
        "đâu": 33, "chỉ": 32, "các": 32, "còn": 32, "cũng": 32, "họ": 32, "như": 32, "thì": 32,
        "thôi": 32, "thế": 32, "vào": 32, "về": 32, "ai": 31, "chuyện": 31, "hắn": 31, "nghĩ": 31,
        "thấy": 31, "đấy": 31, "bị": 30, "chứ": 30, "cần": 30, "ko": 30, "mình": 30, "nếu": 30,
        "nữa": 30, "rất": 30, "à": 30, "chưa": 29, "cả": 29, "lên": 29, "thật": 29, "tới": 29,
        "bạn": 28, "chúng": 28, "hơn": 28, "mọi": 28, "nghe": 28, "nhé": 28, "thứ": 28, "vì": 28,
        "điều": 28, "hãy": 27, "mày": 27, "nên": 27, "từ": 27, "đúng": 27, "đừng": 27, "chết": 26,
        "giờ": 26, "mẹ": 26, "nhiều": 26, "nhà": 26, "tao": 26, "trên": 26, "tìm": 26, "tốt": 26,
        "tớ": 26, "việc": 26, "ơi": 26, "ạ": 26, "bà": 25, "cháu": 25, "dạ": 25, "hay": 25,
        "quá": 25, "sau": 25, "trước": 25, "tên": 25, "vẫn": 25, "bố": 24, "chị": 24, "gặp": 24,
        "khác": 24, "lắm": 24, "ngay": 24, "nhìn": 24, "tin": 24, "xem": 24, "đưa": 24, "gọi": 23,
        "hai": 23, "hiểu": 23, "lúc": 23, "lấy": 23, "lần": 23, "mới": 23, "qua": 23, "rằng": 23,
        "sự": 23, "theo": 23, "chào": 22, "chắc": 22, "cách": 22, "giúp": 22, "hả": 22, "hết": 22,
        "khỏi": 22, "luôn": 22, "ngày": 22, "nha": 22, "nhất": 22, "năm": 22, "sống": 22, "thích": 22,
        "xin": 22, "đc": 22, "ừ": 22, "cha": 21, "cùng": 21, "cứ": 21, "mất": 21, "mấy": 21,
        "nhau": 21, "nơi": 21, "từng": 21, "vâng": 21, "bé": 20, "bên": 20, "bỏ": 20, "chỗ": 20,
        "ngoài": 20, "nhanh": 20, "nhớ": 20, "quay": 20, "tay": 20, "thằng": 20, "tiền": 20, "xe": 20,
        "xuống": 20, "yêu": 20, "ý": 20, "ba": 19, "chẳng": 19, "giống": 19, "hỏi": 19, "kia": 19,
        "xảy": 19, "ăn": 19, "đường": 19, "đều": 19, "ổn": 19, "bắt": 18, "bằng": 18, "chính": 18,
        "chú": 18, "dc": 18, "giữ": 18, "học": 18, "nhỉ": 18, "ok": 18, "vài": 18, "đầu": 18,
        "đồ": 18, "bảo": 17, "chạy": 17, "chờ": 17, "dùng": 17, "lời": 17, "nhận": 17, "phòng": 17,
        "thêm": 17, "tối": 17, "vừa": 17, "đủ": 17, "chiếc": 16, "chơi": 16, "cuộc": 16, "câu": 16,
        "cố": 16, "gái": 16, "gần": 16, "haha": 16, "lớn": 16, "mang": 16, "nay": 16, "ngủ": 16,
        "nè": 16, "nước": 16, "số": 16, "tiếng": 16, "tự": 16, "vs": 16, "vui": 16, "đứa": 16,
        "chút": 15, "dưới": 15, "dừng": 15, "hoặc": 15, "lo": 15, "ngồi": 15, "sợ": 15, "tuyệt": 15,
        "xong": 15, "đánh": 15, "đêm": 15, "đẹp": 15, "đứng": 15, "cơm": 14, "do": 14, "hàng": 14,
        "lâu": 14, "mn": 14, "mệt": 14, "nhỏ": 14, "phía": 14, "rõ": 14, "sáng": 14, "trông": 14,
        "trả": 14, "trời": 14, "tại": 14, "uống": 14, "xa": 14, "đáng": 14, "đợi": 14, "ờ": 14,
        "buổi": 13, "bộ": 13, "coi": 13, "cơ": 13, "cổ": 13, "kìa": 13, "kể": 13, "mau": 13,
        "máy": 13, "mỗi": 13, "phút": 13, "quên": 13, "sắp": 13, "thành": 13, "thử": 13, "trẻ": 13,
        "tàu": 13, "vợ": 13, "yeah": 13, "định": 13, "ồ": 13, "bay": 12, "bài": 12, "bác": 12,
        "hihi": 12, "hơi": 12, "mua": 12, "mặt": 12, "nghỉ": 12, "oke": 12, "phần": 12, "tháng": 12,
        "tui": 12, "tuần": 12, "điên": 12, "bởi": 11, "cao": 11, "chó": 11, "chịu": 11, "cây": 11,
        "giữa": 11, "khá": 11, "loại": 11, "mời": 11, "mở": 11, "rời": 11, "sếp": 11, "thuốc": 11,
        "tránh": 11, "tuổi": 11, "tưởng": 11, "vẻ": 11, "vị": 11, "đặt": 11, "ổng": 11, "bọn": 10,
        "chân": 10, "chọn": 10, "dù": 10, "dậy": 10, "giỏi": 10, "ha": 10, "hehe": 10, "hi": 10,
        "hứa": 10, "khó": 10, "kiểu": 10, "mắt": 10, "ngon": 10, "nhá": 10, "nhóc": 10, "okay": 10,
        "sớm": 10, "thi": 10, "thư": 10, "trường": 10, "tệ": 10, "viết": 10, "á": 10, "đau": 10,
        "đọc": 10, "đời": 10, "ảnh": 10, "ừm": 10, "bán": 9, "báo": 9, "bước": 9, "chi": 9,
        "cửa": 9, "gửi": 9, "hề": 9, "khoan": 9, "lỗi": 9, "món": 9, "mặc": 9, "phim": 9,
        "rượu": 9, "sai": 9, "tạo": 9, "tụi": 9, "yên": 9, "đoán": 9, "đá": 9, "đôi": 9,
        "bệnh": 8, "bức": 8, "bữa": 8, "check": 8, "chuyển": 8, "chả": 8, "cuối": 8, "cà": 8,
        "càng": 8, "dành": 8, "hello": 8, "huhu": 8, "hướng": 8, "họp": 8, "ib": 8, "khoảng": 8,
        "khu": 8, "lòng": 8, "lớp": 8, "muộn": 8, "mơ": 8, "mưa": 8, "nhảy": 8, "nóng": 8,
        "nằm": 8, "nổi": 8, "phê": 8, "quà": 8, "quán": 8, "quả": 8, "rep": 8, "sinh": 8,
        "sorry": 8, "suốt": 8, "thanks": 8, "thường": 8, "thầy": 8, "trễ": 8, "uhm": 8, "vô": 8,
        "ít": 8, "đem": 8, "đói": 8, "ơ": 8, "biển": 7, "chuyến": 7, "chúc": 7, "chồng": 7,
        "chủ": 7, "cũ": 7, "dám": 7, "dạy": 7, "dẫn": 7, "dễ": 7, "ghét": 7, "good": 7,
        "meeting": 7, "màu": 7, "quý": 7, "sách": 7, "team": 7, "thả": 7, "tiếc": 7, "tiếp": 7,
        "trai": 7, "triệu": 7, "trở": 7, "tính": 7, "update": 7, "vòng": 7, "điểm": 7, "đùa": 7,
        "đầy": 7, "bye": 6, "chợ": 6, "cá": 6, "cưng": 6, "cười": 6, "cầm": 6, "cắt": 6,
        "deadline": 6, "dân": 6, "file": 6, "game": 6, "happy": 6, "hoa": 6, "hẳn": 6, "link": 6,
        "love": 6, "lương": 6, "lạnh": 6, "lối": 6, "mạng": 6, "nhóm": 6, "nhật": 6, "nhờ": 6,
        "nắng": 6, "okie": 6, "phá": 6, "phát": 6, "riêng": 6, "ship": 6, "sữa": 6, "thank": 6,
        "tim": 6, "tiến": 6, "tiệc": 6, "trà": 6, "tư": 6, "tết": 6, "viên": 6, "vàng": 6,
        "xấu": 6, "yes": 6, "đám": 6, "đông": 6, "đằng": 6, "ốm": 6, "birthday": 5, "bánh": 5,
        "bún": 5, "call": 5, "chat": 5, "chill": 5, "chung": 5, "chụp": 5, "confirm": 5, "cánh": 5,
        "cưới": 5, "dài": 5, "dây": 5, "email": 5, "già": 5, "giá": 5, "hát": 5, "hì": 5,
        "hình": 5, "hôn": 5, "hẹn": 5, "khóa": 5, "kéo": 5, "like": 5, "ly": 5, "lễ": 5,
        "may": 5, "morning": 5, "mạnh": 5, "ngôi": 5, "nhạc": 5, "nice": 5, "night": 5, "no": 5,
        "nửa": 5, "phép": 5, "phở": 5, "phụ": 5, "project": 5, "siêu": 5, "task": 5, "test": 5,
        "thuộc": 5, "thịt": 5, "trái": 5, "trò": 5, "tóc": 5, "tấm": 5, "uk": 5, "áo": 5,
        "đen": 5, "điện": 5, "đất": 5, "app": 4, "bồ": 4, "clip": 4, "demo": 4, "feedback": 4,
        "fix": 4, "free": 4, "full": 4, "grab": 4, "hử": 4, "kaka": 4, "mail": 4, "meet": 4,
        "miss": 4, "new": 4, "off": 4, "order": 4, "pin": 4, "plan": 4, "report": 4, "review": 4,
        "share": 4, "shop": 4, "support": 4, "sđt": 4, "time": 4, "tắc": 4, "vd": 4, "video": 4,
        "wifi": 4, "wow": 4, "zalo": 4, "add": 3, "best": 3, "book": 3, "cafe": 3, "cmt": 3,
        "content": 3, "cool": 3, "data": 3, "face": 3, "follow": 3, "form": 3, "gym": 3, "hot": 3,
        "inbox": 3, "khát": 3, "live": 3, "lol": 3, "menu": 3, "on": 3, "party": 3, "phone": 3,
        "please": 3, "post": 3, "pro": 3, "reply": 3, "sale": 3, "see": 3, "size": 3, "start": 3,
        "stt": 3, "top": 3, "trip": 3, "vip": 3, "voucher": 3, "web": 3, "welcome": 3, "care": 2,
        "combo": 2, "date": 2, "flex": 2, "kb": 2, "max": 2, "old": 2, "oops": 2, "part": 2,
        "relax": 2, "stop": 2, "store": 2, "story": 2, "vibe": 2, "view": 2,
        // — bổ sung 2026-07-24: địa danh VN/quốc tế, thương hiệu, tech —
        "gòn": 12, "hà": 12, "mỹ": 12, "nội": 12, "sài": 12, "việt": 12, "bàn": 10, "nam": 10,
        "nẵng": 10, "quốc": 10, "trung": 10, "đà": 10, "an": 8, "bình": 8, "bản": 8, "dương": 8,
        "facebook": 8, "google": 8, "huế": 8, "hàn": 8, "hóa": 8, "hải": 8, "hồ": 8, "hội": 8,
        "long": 8, "lạt": 8, "minh": 8, "màn": 8, "nga": 8, "pháp": 8, "phím": 8, "phú": 8,
        "thái": 8, "trang": 8, "youtube": 8, "internet": 7, "iphone": 7, "lan": 7, "laptop": 7, "online": 7,
        "tiktok": 7, "đức": 7, "apple": 6, "chuột": 6, "chí": 6, "code": 6, "hạ": 6, "london": 6,
        "samsung": 6, "shopee": 6, "singapore": 6, "sạc": 6, "viettel": 6, "vũng": 6, "úc": 6, "độ": 6,
        "admin": 5, "arsenal": 5, "biên": 5, "bug": 5, "canada": 5, "chatgpt": 5, "comment": 5, "download": 5,
        "dubai": 5, "fpt": 5, "gmail": 5, "honda": 5, "ipad": 5, "lazada": 5, "livestream": 5, "loan": 5,
        "macbook": 5, "manchester": 5, "momo": 5, "netflix": 5, "nhơn": 5, "offline": 5, "quy": 5, "server": 5,
        "sydney": 5, "sĩ": 5, "thụy": 5, "tokyo": 5, "united": 5, "vinfast": 5, "vingroup": 5, "york": 5,
        "zoom": 5, "ấn": 5, "agribank": 4, "avatar": 4, "backup": 4, "barca": 4, "bidv": 4, "blog": 4,
        "california": 4, "campuchia": 4, "chelsea": 4, "francisco": 4, "liverpool": 4, "login": 4, "louis": 4, "lào": 4,
        "page": 4, "password": 4, "ping": 4, "san": 4, "spotify": 4, "sub": 4, "techcombank": 4, "texas": 4,
        "upload": 4, "vietcombank": 4, "vietjet": 4, "vlog": 4, "vnpay": 4, "vuitton": 4, "washington": 4, "austin": 3,
        "dallas": 3, "houston": 3, "miami": 3, "seattle": 3,
        // — bổ sung 2026-07-24 (2): crypto + họ/tên phổ biến VN —
        "nguyễn": 12, "linh": 10, "lê": 10, "phương": 10, "trần": 10, "hoàng": 9, "hương": 9, "ngọc": 9,
        "phạm": 9, "thảo": 9, "tuấn": 9, "dũng": 8, "hiếu": 8, "hiền": 8, "hùng": 8, "hạnh": 8,
        "khánh": 8, "mai": 8, "mã": 8, "quang": 8, "quỳnh": 8, "sơn": 8, "thu": 8, "tâm": 8,
        "vân": 8, "ví": 8, "vũ": 8, "bùi": 7, "công": 7, "huỳnh": 7, "lâm": 7, "ngô": 7,
        "nhi": 7, "phan": 7, "phong": 7, "phúc": 7, "thúy": 7, "trịnh": 7, "tú": 7, "võ": 7,
        "đặng": 7, "đỗ": 7, "bitcoin": 6, "khoa": 6, "kiên": 6, "lý": 6, "my": 6, "sàn": 6,
        "trâm": 6, "yến": 6, "đinh": 6, "đào": 6, "coin": 5, "crypto": 5, "lệnh": 5, "binance": 4,
        "blockchain": 4, "eth": 4, "ethereum": 4, "token": 4, "usdt": 4,
        // — bổ sung 2026-07-24 (3): thương hiệu nội bộ —
        "printik": 6, "senprints": 6,
        // — bổ sung 2026-07-24 (4): tên đệm —
        "văn": 10, "thị": 9, "hồng": 7, "kim": 7, "xuân": 7, "duy": 6, "hữu": 6, "thùy": 6,
        "đình": 6, "bá": 5, "bích": 5, "diệu": 5, "trọng": 5, "khắc": 4,
        // — bổ sung 2026-07-24 (5): hệ điều hành / phần mềm —
        "windows": 6, "macos": 6, "ios": 6, "android": 6, "chrome": 5, "linux": 4, "safari": 4, "excel": 4, "word": 4,
        "github": 5, "claude": 5, "tesla": 5, "openai": 4, "anthropic": 3, "yahoo": 4, "outlook": 4, "hotmail": 3,
        "đcm": 8, "đm": 8, "dm": 8, "vcl": 10, "vkl": 6, "vl": 12, "clgt": 4, "cứt": 8, "vãi": 10, "cmnr": 5, "chửi": 8, "cướp": 6, "giết": 8, "hiếp": 3, "trộm": 5, "fuck": 5, "shit": 5, "lừa": 7, "đểu": 5, "xạo": 6,
        "lồn": 5, "địt": 5, "đụ": 4, "đĩ": 4, "tml": 5, "sml": 5, "dâm": 4, "dê": 4, "tục": 4, "tĩu": 3, "thối": 5, "um": 3, "rắm": 4, "sấp": 4, "ngu": 8, "si": 4, "đần": 4, "độn": 3, "tha": 4, "khốn": 5, "nạn": 5, "má": 8,
    ] }

    static var bigrams: [(String, String, Int)] { [
        ("chúng", "ta", 49), ("có", "thể", 46), ("chúng", "tôi", 41), ("cảm", "ơn", 40), ("hôm", "nay", 40),
        ("không", "thể", 36), ("anh", "ơi", 35), ("xin", "lỗi", 35), ("tất", "cả", 33), ("em", "ơi", 32),
        ("được", "rồi", 30), ("bao", "giờ", 29), ("tại", "sao", 29), ("bây", "giờ", 28), ("không", "sao", 28),
        ("ngày", "mai", 28), ("thế", "nào", 28), ("chị", "ơi", 25), ("cám", "ơn", 25), ("em", "nhé", 25),
        ("hôm", "qua", 25), ("làm", "gì", 25), ("ngủ", "ngon", 25), ("nói", "chuyện", 25), ("thời", "gian", 25),
        ("có", "lẽ", 23), ("làm", "việc", 23), ("anh", "nhé", 22), ("bắt", "đầu", 22), ("vấn", "đề", 22),
        ("ăn", "cơm", 22), ("đi", "làm", 22), ("như", "vậy", 21), ("thế", "giới", 21), ("bạn", "ơi", 20),
        ("trời", "ơi", 20), ("về", "nhà", 20), ("xin", "chào", 20), ("cuối", "cùng", 19), ("gia", "đình", 19),
        ("làm", "sao", 19), ("sẵn", "sàng", 19), ("anh", "đang", 18), ("bảo", "vệ", 18), ("bất", "cứ", 18),
        ("cho", "em", 18), ("em", "đang", 18), ("gì", "vậy", 18), ("mẹ", "ơi", 18), ("thực", "sự", 18),
        ("tối", "nay", 18), ("xong", "rồi", 18), ("ăn", "chưa", 18), ("đi", "chơi", 18), ("đi", "học", 18),
        ("đi", "ngủ", 18), ("đi", "ăn", 18), ("được", "không", 18), ("đầu", "tiên", 18), ("ở", "nhà", 18),
        ("ở", "đâu", 18), ("an", "toàn", 17), ("bởi", "vì", 17), ("chắc", "chắn", 17), ("con", "trai", 17),
        ("cảm", "thấy", 17), ("duy", "nhất", 17), ("một", "chút", 17), ("quan", "tâm", 17), ("bao", "nhiêu", 16),
        ("bác", "sĩ", 16), ("phụ", "nữ", 16), ("quan", "trọng", 16), ("thay", "đổi", 16), ("thật", "sự", 16),
        ("trở", "lại", 16), ("anh", "yêu", 15), ("biết", "rồi", 15), ("buồn", "ngủ", 15), ("buổi", "sáng", 15),
        ("cho", "anh", 15), ("chúc", "mừng", 15), ("chúc", "ngủ", 15), ("con", "gái", 15), ("cuối", "tuần", 15),
        ("cà", "phê", 15), ("công", "việc", 15), ("gì", "thế", 15), ("gì", "đó", 15), ("không", "được", 15),
        ("khỏe", "không", 15), ("kiểm", "tra", 15), ("kế", "hoạch", 15), ("kết", "thúc", 15), ("mình", "đang", 15),
        ("mấy", "giờ", 15), ("mệt", "quá", 15), ("rồi", "nhé", 15), ("sao", "rồi", 15), ("sao", "đâu", 15),
        ("sinh", "nhật", 15), ("sáng", "nay", 15), ("thank", "you", 15), ("trở", "thành", 15), ("yêu", "em", 15),
        ("ăn", "gì", 15), ("đi", "đâu", 15), ("điện", "thoại", 15), ("đàn", "ông", 15), ("đúng", "rồi", 15),
        ("đồng", "ý", 15), ("ở", "đây", 15), ("anh", "à", 14), ("chuẩn", "bị", 14), ("con", "người", 14),
        ("cơ", "hội", 14), ("em", "à", 14), ("lý", "do", 14), ("người", "ta", 14), ("thành", "phố", 14),
        ("tiếp", "tục", 14), ("trả", "lời", 14), ("tuyệt", "vời", 14), ("tất", "nhiên", 14), ("ăn", "trưa", 14),
        ("cuộc", "sống", 13), ("hoàn", "toàn", 13), ("hy", "vọng", 13), ("quyết", "định", 13), ("sự", "thật", 13),
        ("anh", "nha", 12), ("bình", "tĩnh", 12), ("chiều", "nay", 12), ("cho", "mình", 12), ("chào", "buổi", 12),
        ("chính", "xác", 12), ("cẩn", "thận", 12), ("cố", "lên", 12), ("của", "anh", 12), ("của", "em", 12),
        ("em", "nha", 12), ("gì", "không", 12), ("gọi", "điện", 12), ("gửi", "cho", 12), ("hiểu", "rồi", 12),
        ("lát", "nữa", 12), ("lúc", "nào", 12), ("mình", "đi", 12), ("nguy", "hiểm", 12), ("ngủ", "chưa", 12),
        ("nhắn", "tin", 12), ("phải", "không", 12), ("rảnh", "không", 12), ("rồi", "ạ", 12), ("sức", "khỏe", 12),
        ("tuần", "này", 12), ("tuần", "sau", 12), ("tí", "nữa", 12), ("tạm", "biệt", 12), ("vui", "quá", 12),
        ("về", "chưa", 12), ("về", "rồi", 12), ("xong", "chưa", 12), ("yêu", "anh", 12), ("ăn", "sáng", 12),
        ("ăn", "tối", 12), ("đâu", "rồi", 12), ("đúng", "không", 12), ("đẹp", "quá", 12), ("ơn", "anh", 12),
        ("ơn", "nhiều", 12), ("ơn", "nhé", 12), ("ơn", "ạ", 12), ("may", "mắn", 11), ("đúng", "vậy", 11),
        ("đặc", "biệt", 11), ("buổi", "tối", 10), ("chán", "quá", 10), ("chút", "nữa", 10), ("cố", "gắng", 10),
        ("của", "mình", 10), ("dễ", "thương", 10), ("giờ", "rồi", 10), ("good", "morning", 10), ("good", "night", 10),
        ("gì", "nữa", 10), ("gì", "đâu", 10), ("gặp", "lại", 10), ("gặp", "nhau", 10), ("hay", "quá", 10),
        ("khả", "năng", 10), ("nhớ", "anh", 10), ("nhớ", "em", 10), ("nói", "dối", 10), ("rồi", "nha", 10),
        ("rồi", "đó", 10), ("sáng", "mai", 10), ("sếp", "ơi", 10), ("thì", "sao", 10), ("thậm", "chí", 10),
        ("tin", "nhắn", 10), ("trà", "sữa", 10), ("trời", "mưa", 10), ("về", "quê", 10), ("với", "anh", 10),
        ("với", "em", 10), ("với", "nhau", 10), ("yêu", "cầu", 10), ("đi", "nhé", 10), ("đi", "về", 10),
        ("đói", "quá", 10), ("đồ", "ăn", 10), ("ơn", "bạn", 10), ("ơn", "em", 10), ("ổn", "không", 10),
        ("bình", "thường", 9), ("bí", "mật", 9), ("câu", "chuyện", 9), ("liên", "quan", 9), ("máy", "bay", 9),
        ("một", "mình", 9), ("thông", "tin", 9), ("vị", "trí", 9), ("anh", "em", 8), ("buổi", "chiều", 8),
        ("bản", "thân", 8), ("bận", "không", 8), ("bận", "quá", 8), ("chuyển", "khoản", 8), ("chúc", "anh", 8),
        ("chúc", "em", 8), ("chờ", "chút", 8), ("cuộc", "họp", 8), ("cảm", "giác", 8), ("cậu", "ơi", 8),
        ("gì", "chưa", 8), ("gửi", "anh", 8), ("gửi", "em", 8), ("happy", "birthday", 8), ("hoạt", "động", 8),
        ("hẹn", "gặp", 8), ("love", "you", 8), ("là", "được", 8), ("lỗi", "nhé", 8), ("lựa", "chọn", 8),
        ("mai", "nhé", 8), ("muộn", "rồi", 8), ("mình", "về", 8), ("mình", "ăn", 8), ("mừng", "sinh", 8),
        ("nghỉ", "ngơi", 8), ("ngủ", "dậy", 8), ("nha", "anh", 8), ("nha", "em", 8), ("nhanh", "lên", 8),
        ("nhà", "anh", 8), ("nhà", "em", 8), ("nhà", "mình", 8), ("như", "nào", 8), ("nhớ", "nhé", 8),
        ("nóng", "quá", 8), ("ok", "nhé", 8), ("rõ", "ràng", 8), ("rắc", "rối", 8), ("see", "you", 8),
        ("sử", "dụng", 8), ("tham", "gia", 8), ("tháng", "sau", 8), ("thôi", "nhé", 8), ("thật", "à", 8),
        ("trưa", "nay", 8), ("từ", "từ", 8), ("tự", "do", 8), ("vậy", "hả", 8), ("ăn", "uống", 8),
        ("đi", "họp", 8), ("đêm", "nay", 8), ("được", "chưa", 8), ("đợi", "anh", 8), ("đợi", "em", 8),
        ("ơn", "chị", 8), ("ổn", "mà", 8), ("bao", "lâu", 7), ("cuộc", "đời", 7), ("có", "vẻ", 7),
        ("công", "ty", 7), ("giúp", "đỡ", 7), ("giải", "quyết", 7), ("giải", "thích", 7), ("hành", "động", 7),
        ("hệ", "thống", 7), ("lo", "lắng", 7), ("nghĩa", "là", 7), ("suy", "nghĩ", 7), ("toàn", "bộ", 7),
        ("tình", "yêu", 7), ("buổi", "trưa", 6), ("cho", "tớ", 6), ("chuyển", "tiền", 6), ("chưa", "được", 6),
        ("chờ", "anh", 6), ("chờ", "em", 6), ("chụp", "ảnh", 6), ("có", "khỏe", 6), ("di", "chuyển", 6),
        ("good", "job", 6), ("good", "luck", 6), ("gửi", "nhé", 6), ("hạnh", "phúc", 6), ("khỏe", "chứ", 6),
        ("liên", "lạc", 6), ("lỗi", "anh", 6), ("lỗi", "em", 6), ("miss", "you", 6), ("mua", "gì", 6),
        ("mua", "đồ", 6), ("một", "cách", 6), ("nghỉ", "phép", 6), ("ngủ", "sớm", 6), ("no", "problem", 6),
        ("of", "course", 6), ("rảnh", "chưa", 6), ("tan", "làm", 6), ("theo", "dõi", 6), ("thành", "công", 6),
        ("thôi", "được", 6), ("thông", "minh", 6), ("thật", "hả", 6), ("thời", "tiết", 6), ("thực", "hiện", 6),
        ("trễ", "rồi", 6), ("trời", "nắng", 6), ("tương", "lai", 6), ("tối", "mai", 6), ("uống", "cà", 6),
        ("uống", "nước", 6), ("vui", "vẻ", 6), ("về", "sớm", 6), ("với", "mình", 6), ("xuất", "hiện", 6),
        ("được", "đó", 6), ("đối", "với", 6), ("báo", "cáo", 5), ("check", "lại", 5), ("chú", "ý", 5),
        ("chấp", "nhận", 5), ("dĩ", "nhiên", 5), ("giữ", "gìn", 5), ("gặp", "sau", 5), ("gửi", "ảnh", 5),
        ("hình", "ảnh", 5), ("khó", "khăn", 5), ("lỗi", "nha", 5), ("một", "số", 5), ("nhất", "trí", 5),
        ("ok", "anh", 5), ("ok", "em", 5), ("ok", "luôn", 5), ("phát", "hiện", 5), ("thật", "ra", 5),
        ("thế", "là", 5), ("thế", "thì", 5), ("tiếp", "theo", 5), ("tìm", "kiếm", 5), ("tổ", "chức", 5),
        ("văn", "phòng", 5), ("ít", "nhất", 5), ("đơn", "giản", 5), ("ừ", "nhé", 5), ("bệnh", "viện", 4),
        ("bố", "mẹ", 4), ("check", "in", 4), ("chào", "mừng", 4), ("chăm", "sóc", 4), ("dù", "sao", 4),
        ("hay", "là", 4), ("ngu", "ngốc", 4), ("quan", "hệ", 4), ("sai", "lầm", 4), ("team", "mình", 4),
        ("thú", "vị", 4), ("trách", "nhiệm", 4), ("trở", "nên", 4), ("tập", "trung", 4), ("đúng", "thế", 4),
        ("đặt", "đồ", 4), ("bất", "kỳ", 3), ("deadline", "rồi", 3), ("hoàn", "hảo", 3), ("ngạc", "nhiên", 3),
        ("nếu", "như", 3), ("tin", "tưởng", 3), ("tưởng", "tượng", 3), ("tồn", "tại", 3),
        // — bổ sung 2026-07-24: tên đa âm tiết (địa danh, thương hiệu, cụm tech) —
        ("việt", "nam", 15), ("hà", "nội", 14), ("sài", "gòn", 14), ("hồ", "chí", 10), ("chí", "minh", 10),
        ("đà", "nẵng", 12), ("đà", "lạt", 11), ("nha", "trang", 10), ("thanh", "hóa", 8), ("hội", "an", 8),
        ("phú", "quốc", 9), ("cần", "thơ", 8), ("vũng", "tàu", 8), ("hải", "phòng", 8), ("hạ", "long", 7),
        ("quy", "nhơn", 6), ("biên", "hòa", 5), ("bình", "dương", 6), ("trung", "quốc", 10), ("hàn", "quốc", 9),
        ("thái", "lan", 9), ("nhật", "bản", 8), ("đài", "loan", 5), ("ấn", "độ", 6), ("thụy", "sĩ", 6),
        ("new", "york", 8), ("san", "francisco", 6), ("manchester", "united", 8), ("louis", "vuitton", 6), ("bàn", "phím", 8),
        ("màn", "hình", 8), ("tai", "nghe", 6),
        // — bổ sung 2026-07-24 (2): tên ghép + cụm crypto —
        ("tuấn", "anh", 9), ("quốc", "anh", 5), ("minh", "anh", 6), ("ngọc", "anh", 6), ("phương", "anh", 6),
        ("lan", "anh", 5), ("hải", "anh", 4), ("mai", "anh", 5), ("thanh", "tùng", 5), ("minh", "tuấn", 5),
        ("văn", "nam", 4), ("thị", "hoa", 3), ("tiền", "mã", 5), ("mã", "hóa", 6), ("đồng", "coin", 4),
        ("ví", "điện", 4), ("điện", "tử", 6), ("sàn", "binance", 3), ("giá", "bitcoin", 4), ("chơi", "coin", 4),
        // — bổ sung 2026-07-24 (4): họ→đệm, đệm→tên —
        ("nguyễn", "văn", 10), ("nguyễn", "thị", 10), ("trần", "văn", 8), ("trần", "thị", 8), ("lê", "văn", 8),
        ("lê", "thị", 8), ("phạm", "văn", 7), ("phạm", "thị", 7), ("hoàng", "văn", 6), ("hoàng", "thị", 6),
        ("vũ", "văn", 5), ("vũ", "thị", 5), ("đặng", "văn", 5), ("đặng", "thị", 5), ("bùi", "văn", 4),
        ("bùi", "thị", 4), ("nguyễn", "đức", 6), ("nguyễn", "minh", 6), ("nguyễn", "ngọc", 6), ("nguyễn", "hữu", 5),
        ("nguyễn", "xuân", 5), ("nguyễn", "quang", 5), ("nguyễn", "thanh", 5), ("nguyễn", "hoàng", 5), ("văn", "hùng", 5),
        ("văn", "tuấn", 5), ("văn", "dũng", 4), ("văn", "sơn", 4), ("thị", "hương", 5), ("thị", "lan", 5),
        ("thị", "thu", 5), ("thị", "ngọc", 4), ("thị", "hồng", 4), ("thị", "phương", 4), ("xuân", "trường", 4),
        ("đình", "phong", 3),
        ("như", "cứt", 6), ("ngon", "vl", 8), ("mệt", "vl", 6), ("đau", "vcl", 4), ("fuck", "you", 6), ("vãi", "cả", 4), ("lừa", "đảo", 7), ("cướp", "giật", 4),
        ("vãi", "lồn", 5), ("địt", "mẹ", 5), ("bố", "mày", 7), ("con", "đĩ", 4), ("thằng", "mặt", 4), ("mặt", "lồn", 4), ("dâm", "dê", 4), ("tục", "tĩu", 4), ("cả", "lồn", 4), ("đụ", "má", 4), ("má", "mày", 4), ("thối", "um", 3), ("đánh", "rắm", 4), ("sấp", "mặt", 5), ("ngu", "si", 4), ("đần", "độn", 4), ("thối", "tha", 4), ("khốn", "nạn", 6), ("mất", "dạy", 4),
    ] }
}
