#!/usr/bin/env python3
"""Generate windows/engine/tests/ported_cases.inc — the hand-written expectations of
TelexCore's Swift XCTests, as a C++ table.

Source: android/telexcore/src/test/kotlin/.../SwiftPortedTests.kt, which is itself
GENERATED from the Swift tests by android/telexcore/scripts/port-swift-tests.py (same
helper mapping). Regenerate that first when the Swift tests change, then run:
    python3 windows/engine/tools/port_tests.py
"""
import os, re

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.abspath(os.path.join(here, "..", "..", ".."))
src = os.path.join(root, "android", "telexcore", "src", "test", "kotlin", "com", "viettelex",
                   "telexcore", "SwiftPortedTests.kt")
out = os.path.join(here, "..", "tests", "ported_cases.inc")

LIT = r'"((?:[^"\\]|\\.)*)"'
eng = re.compile(r'assert(Equals|NotEquals)\(' + LIT + r', (\w+)\(' + LIT +
                 r'(?:, (\d+))?(?:, autoRestore = (true|false))?\) \{([^}]*)\}\)')
val = re.compile(r'assert(True|False)\(' + LIT + r', SyllableValidator\.(isValidSyllable|isValidPrefix)\(' +
                 LIT + r'(?:, teencode = (true|false))?\)\)')
cls_re = re.compile(r'^class (\w+)')
fn_re = re.compile(r'@Test fun (\w+)\(')

FLAG = {"freeMarking": "F", "modernTone": "M", "liveSpellCheck": "L", "simpleTelex": "S",
        "teencode": "t", "quickTelex": "Q", "bracketVowels": "B", "vniMode": "V",
        "contextualEnglish": "C", "englishWordRestore": "e", "collisionPrefersVietnamese": "P"}
DEFAULT = {"teencode": True, "englishWordRestore": True}

def unesc(s):
    return s.replace("\\$", "$")

def cstr(s):
    # Source files are UTF-8 (MSVC: /utf-8); only quote/backslash/trigraph need escaping.
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("?", "\\?") + '"'

rows = []
cls = fn = ""
for line in open(src, encoding="utf-8"):
    m = cls_re.match(line)
    if m: cls = m.group(1); continue
    m = fn_re.search(line)
    if m: fn = m.group(1); continue
    m = eng.search(line)
    if m:
        neg, exp, helper, keys, n, auto, cfg = m.groups()
        flags = ""
        for stmt in [s.strip() for s in cfg.split(";") if s.strip()]:
            k, v = [x.strip() for x in stmt.split("=")]
            on = v == "true"
            if on != DEFAULT.get(k, False):
                flags += FLAG[k]
        rows.append(f'  {{"{helper}", "{flags}", {cstr(unesc(keys))}, {cstr(unesc(exp))}, '
                    f'{1 if neg == "NotEquals" else 0}, {n or 1}, {0 if auto == "false" else 1}, "{cls}.{fn}"}},')
        continue
    m = val.search(line)
    if m:
        tf, _, fnname, word, tc = m.groups()
        rows.append(f'  {{"{fnname}", "{"t" if tc == "false" else ""}", {cstr(unesc(word))}, '
                    f'"{1 if tf == "True" else 0}", 0, 0, 1, "{cls}.{fn}"}},')
        continue
    if "assert" in line and "fun " not in line and not line.startswith("import"):
        raise SystemExit("unparsed assertion: " + line.strip())

with open(out, "w", encoding="utf-8") as f:
    f.write("// GENERATED by windows/engine/tools/port_tests.py — DO NOT EDIT.\n")
    f.write("// {helper, flags, input, expected, negate, n, autoRestore, origin}\n")
    f.write("\n".join(rows) + "\n")
print(f"{len(rows)} cases")
